### ISSUE TITLE
client.sendOutputEvent not found

### ISSUE THREAD

**Issue by Alovantous** [Azure/azure-iot-sdk-node#1045]
Has sendOutputEvent been depreciated? For some reason I can't call it without getting this error:

```
/app/app.js:54
      client.sendOutputEvent('output1', message,     printResultFor('Sending received message'));
             ^

TypeError: client.sendOutputEvent is not a function
    at Timeout._onTimeout (/app/app.js:54:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Here is the code I am using:

```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

'use strict';

var fs = require('fs');
var Protocol = require('azure-iot-device-mqtt').Mqtt;
// Uncomment one of these transports and then change it in fromConnectionString to test other transports
// var Protocol = require('azure-iot-device-http').Http;
//var Protocol = require('azure-iot-device-amqp').Amqp;
var Client = require('azure-iot-device').Client;
var Message = require('azure-iot-device').Message;

var deviceConnectionString = "HostName=ESC-int-001.azure-devices.net;DeviceId=Virtual_Humidity_Simulator;SharedAccessKey=removed;GatewayHostName=edge"

// Path to the Edge "owner" root CA certificate
var edge_ca_cert_path = "./azure-iot-test-only.root.ca.cert.pem";

// fromConnectionString must specify a transport constructor, coming from any transport package.
var client = Client.fromConnectionString(deviceConnectionString, Protocol);

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    console.log('Client connected');
    client.on('message', function (msg) {
      console.log('Id: ' + msg.messageId + ' Body: ' + msg.data);
      // When using MQTT the following line is a no-op.
      client.complete(msg, printResultFor('completed'));
      // The AMQP and HTTP transports also have the notion of completing, rejecting or abandoning the message.
      // When completing a message, the service that sent the C2D message is notified that the message has been processed.
      // When rejecting a message, the service that sent the C2D message is notified that the message won't be processed by the device. the method to use is client.reject(msg, callback).
      // When abandoning the message, IoT Hub will immediately try to resend it. The method to use is client.abandon(msg, callback).
      // MQTT is simpler: it accepts the message by default, and doesn't support rejecting or abandoning a message.
    });

    // Create a message and send it to the IoT Hub every two seconds
    var sendInterval = setInterval(function () {
      var humidity = 60 + (Math.random() * 20); // range: [60, 80]
      var data = JSON.stringify({ deviceId: 'Virtual_Humidity_Simulator', humidity: humidity });
      var message = new Message(data);
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message, printResultFor('send'));
      
      console.log("1")
      client.sendOutputEvent('output1', message,     printResultFor('Sending received message'));
      console.log("2")
      client.sendOutputEvent('humidity1',message);
      console.log("3")
      client.sendOutputEvent('humidity2',message, printResultFor('send'));
      console.log("4")
      client.sendOutputEvent('humidity3', outputMsg, printResultFor('Sending received message'));
      console.log("5")
      client.sendOutputEvent('humidity')
      
      console.log("5")
    }, 2000);

    client.on('error', function (err) {
      console.error(err.message);
    });

    client.on('disconnect', function () {
      clearInterval(sendInterval);
      client.removeAllListeners();
      client.open(connectCallback);
    });
  }
};

// Provide the Azure IoT device client via setOptions with the X509
// Edge root CA certificate that was used to setup the Edge runtime
var options = {
  ca : fs.readFileSync(edge_ca_cert_path, 'utf-8'),
};

client.setOptions(options, function(err) {
  if (err) {
    console.log('SetOptions Error: ' + err);
  } else {
    client.open(connectCallback);
  }
});

// Helper function to print results in the console
function printResultFor(op) {
  return function printResult(err, res) {
    if (err) console.log(op + ' error: ' + err.toString());
    if (res) console.log(op + ' status: ' + res.constructor.name);
  };
}
```

**Comment by anthonyvercolano** [comment]
const ModuleClient =  require('azure-iot-devices').ModuleClient;

const moduleClient = ModuleClient.fromConnectionString(connectionString, transport);

**Comment by Alovantous** [comment]
I will try that, so my issue seems to be similar to the issue on question 1016 using the wrong type of client. 

I have read though the 1016 question and my understanding is that if I am using the IoT Edge Hub I should use Moduleclient as per your message and if I am going direct to cloud us Client?

**Comment by YoDaMa** [comment]
@alovantous correct :)
