### ISSUE TITLE
uploadToBlob throws an error, Invalid or unexpected token at createScript (vm.js:74:10) 

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdk-node#130]
# Context
- **OS and version used:** Ubuntu 16.04
- **Node.js version:** 8.5
- **npm version:** 5.3.0
- **list of installed packages:** 
├─┬ azure-iot-device@1.2.0
│ ├── azure-iot-common@1.2.1
│ ├─┬ azure-iot-http-base@1.2.0
│ │ ├── azure-iot-common@1.2.0
│ │ ├── debug@2.6.8 deduped
│ │ └── uuid@2.0.3
│ ├─┬ azure-storage@2.6.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── inherits@2.0.3 deduped
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2 deduped
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31 deduped
│ │ │ └── util-deprecate@1.0.2
│ │ ├── request@2.81.0 deduped
│ │ ├── underscore@1.8.3
│ │ ├── uuid@3.1.0 deduped
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── lodash@4.17.4 deduped
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-mqtt@1.2.1
│ ├── azure-iot-common@1.2.1 deduped
│ ├── azure-iot-device@1.2.0 deduped
│ ├─┬ azure-iot-mqtt-base@1.2.1
│ │ ├── azure-iot-common@1.2.1 deduped
│ │ ├── machina@2.0.0 deduped
│ │ └─┬ mqtt@2.13.1
│ │   ├─┬ commist@1.0.0
│ │   │ ├── leven@1.0.2
│ │   │ └── minimist@1.2.0 deduped
│ │   ├── concat-stream@1.6.0 deduped
│ │   ├─┬ end-of-stream@1.4.0
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.1 deduped
│ │   │ │ ├── glob@7.1.2 deduped
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.0.6 deduped
│ │   │ │ ├─┬ pumpify@1.3.5
│ │   │ │ │ ├── duplexify@3.5.1 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ └── pump@1.0.2 deduped
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.1
│ │   │ │ │ ├─┬ extend-shallow@2.0.1
│ │   │ │ │ │ └── is-extendable@0.1.1
│ │   │ │ │ ├─┬ is-absolute@0.2.6
│ │   │ │ │ │ ├─┬ is-relative@0.2.1
│ │   │ │ │ │ │ └─┬ is-unc-path@0.1.2
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@0.2.0
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.2.1
│ │   │ │   ├── json-stable-stringify@1.0.1 deduped
│ │   │ │   └─┬ through2-filter@2.0.0
│ │   │ │     ├── through2@2.0.3 deduped
│ │   │ │     └── xtend@4.0.1 deduped
│ │   │ ├─┬ through2@2.0.3
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ └── xtend@4.0.1 deduped
│ │   │ └── xtend@4.0.1 deduped
│ │   ├── inherits@2.0.3 deduped
│ │   ├── minimist@1.2.0
│ │   ├─┬ mqtt-packet@5.4.0
│ │   │ ├─┬ bl@1.2.1
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ └── safe-buffer@5.1.1 deduped
│ │   ├─┬ pump@1.0.2
│ │   │ ├── end-of-stream@1.4.0 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.3
│ │   │ ├── core-util-is@1.0.2 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── isarray@1.0.0 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ string_decoder@1.0.3
│ │   │ │ └── safe-buffer@5.1.1 deduped
│ │   │ └── util-deprecate@1.0.2 deduped
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@2.2.0
│ │   │ └── through2@2.0.3 deduped
│ │   ├─┬ websocket-stream@5.1.1
│ │   │ ├─┬ duplexify@3.5.1
│ │   │ │ ├── end-of-stream@1.4.0 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── readable-stream@2.0.6 deduped
│ │   │ │ └── stream-shift@1.0.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ ws@3.2.0
│ │   │ │ ├── async-limiter@1.0.0
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ └── ultron@1.1.0
│ │   │ └── xtend@4.0.1 deduped
│ │   └── xtend@4.0.1 deduped
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0 deduped
│ └── machina@2.0.0 deduped

# Description of the issue:
When uploadToblob is called it throws uncaught exception as below. Please let me know if you need more info. Thanks

# Code sample exhibiting the issue:
```
import { Client, ConnectionString, Message } from 'azure-iot-device';
import { Mqtt } from 'azure-iot-device-mqtt';

const sas = generateSAS(); //local method that creates SAS
let _client = Client.fromSharedAccessSignature(sas, Mqtt);

// other code to setup the fileStream and related data.... 

_client.uploadToBlob(filename, fileStream, fileStats.size, (err2) => {
    if (err2) {
        logger.error(`UploadData Error`, err2.message);
    } else {
        logger.info(`UploadData Success`);
    }
});
```
# Console log of the issue:
```
PROCESS uncaught exception /home/app/node_modules/validator/validator.js:1
(function (exports, require, module, __filename, __dirname) { HttpServer2onERKN2v820FunctionCallbackInfoINS0_5ValueEEE

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/app/node_modules/azure-storage/lib/common/util/validate.js:26:13) /home/app/node_modules/validator/validator.js:1
(function (exports, require, module, __filename, __dirname) { HttpServer2onERKN2v820FunctionCallbackInfoINS0_5ValueEEE
```

**Comment by bmrpatel** [comment]
I investigated further and realized that the module was corrupted. I reinstalled it and is working fine now. Thanks
