### ISSUE TITLE
AMQP EventEmitter memory leak detected

### ISSUE THREAD

**Issue by dsjh** [Azure/azure-iot-sdk-node#141]
# Context
- **OS and version used:** Debian Jessie (8) | 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux 
- **Node.js version:** 4.32
- **npm version:** 2.14.12
- **list of installed packages:** azure-iot-device-mqtt@1.2.1 node_modules/azure-iot-device-mqtt
├── azure-iot-common@1.2.1
├── debug@3.1.0 (ms@2.0.0)
├── azure-iot-mqtt-base@1.2.1 (mqtt@2.13.1)
└── machina@2.0.0 (lodash@3.10.1)
azure-iot-device@1.2.0 node_modules/azure-iot-device
├── debug@3.1.0 (ms@2.0.0)
├── traverse@0.6.6
├── azure-iot-common@1.2.1
├── azure-iot-http-base@1.2.0 (uuid@2.0.3, debug@2.6.9, azure-iot-common@1.2.0)
├── azure-storage@2.6.0 (extend@1.2.1, underscore@1.8.3, xmlbuilder@0.4.3, browserify-mime@1.2.9, validator@3.35.0, uuid@3.1.0, readable-stream@2.0.6, md5.js@1.3.4, json-edm-parser@0.1.2, xml2js@0.2.7)
├── machina@2.0.0 (lodash@3.10.1)
└── lodash@4.17.4
azure-iot-device-amqp@1.2.1 node_modules/azure-iot-device-amqp
├── uuid@3.1.0
├── azure-iot-common@1.2.1
├── debug@3.1.0 (ms@2.0.0)
├── machina@2.0.0 (lodash@3.10.1)
├── async@2.5.0 (lodash@4.17.4)
└── azure-iot-amqp-base@1.2.1 (amqp10-transport-ws@0.0.5, bluebird@3.5.1, amqp10@3.5.3)
- **cloned repo: N/A

# Description of the issue:
Using AMQP, if we block all inbound/outbound traffic there is a memory leak warning approx 5 minutes after the connection is blocked. The error appears to stop the client.on("disconnect") firing and when re-connecting the messages come through fine.

# Code sample exhibiting the issue:
We are running the sample code here: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

# Console log of the issue:
```
(node) warning: possible EventEmitter memory leak detected. 11 disconnected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at AMQPClient.addListener (events.js:239:17)
    at Amqp._fsm.machina.Fsm.states.connecting._onEnter (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:163:37)
    at _.extend.transition (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:653:28)
    at Fsm.(anonymous function) [as transition] (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:466:63)
    at Amqp._fsm.machina.Fsm.states.disconnected.connect (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:109:36)
    at _.extend.handle (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:613:25)
    at Fsm.(anonymous function) [as handle] (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:466:63)
    at Amqp.connect (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:397:19)
    at Amqp._this._fsm.machina.Fsm.states.connecting._onEnter (/var/anpr/node_modules/azure-iot-device-amqp/lib/amqp.js:216:37)
    at _.extend.transition (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:653:28)
    at Fsm.(anonymous function) [as transition] (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:466:63)
    at Amqp._this._fsm.machina.Fsm.states.disconnected.connect (/var/anpr/node_modules/azure-iot-device-amqp/lib/amqp.js:118:77)
    at _.extend.handle (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:613:25)
    at Fsm.(anonymous function) [as handle] (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:466:63)
    at Amqp._this._fsm.machina.Fsm.states.disconnected.enableMethods (/var/anpr/node_modules/azure-iot-device-amqp/lib/amqp.js:180:36)
    at _.extend.handle (/var/anpr/node_modules/azure-iot-device-amqp/node_modules/machina/lib/machina.js:613:25)
```

**Comment by pierreca** [comment]
@dsjh thanks for opening this issue and being very clear with the repro steps. I've already setup a similar experiment to figure out what's going on and will keep you posted.

**Comment by pierreca** [comment]
Just submitted a fix for review... Will label the issue as "fix checked in" when it's merge into master and close it when we release new packages.

**Comment by pierreca** [comment]
A new release including the fix has been published:
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-11-15

Thanks again for your help!
