### ISSUE TITLE
can't use azure-iothub lib in azure web app

### ISSUE THREAD

**Issue by qusp66** [Azure/azure-iot-sdk-node#191]
# Context
- **OS and version used:** azure api app (Microsoft Windows [Version 10.0.14393]) - same code works on my laptop (node v9.3.0)
- **Node.js version:** v0.10.40 
- **npm version:** 1.4.28
- **list of installed packages:**     
    "azure-iothub": "^1.2.3",
    "body-parser": "~1.18.2",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "express": "~4.15.5",
# Description of the issue:
Internal server error on API App
Should be the node version but it all worked about a month ago....

# Code sample exhibiting the issue:
used sample code from the SDK to register a new device in iothub registry

# Console log of the issue:
TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (util.js:511:43)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\azure-iothub\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\streams\receiver_stream.js:16:6)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\azure-iothub\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\amqp_client.js:10:22)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\azure-iothub\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\index.js:3:14)

**Comment by pierreca** [comment]
Hi @qusp66 
it looks like this is a problem with a dependency of a dependency, you're using a very old version of node (0.10) that is not supported anymore. Can you please upgrade the version of node and see if it fixes it? I can't force dependencies, let alone dependencies of dependencies, to support deprecated versions of the runtime.

**Comment by qusp66** [comment]
yes, what is really weird is why would azure app service would pick up a pre-historic version of node by defaut :(

**Comment by michaeljqzq** [comment]
Same problem, I use createOrUpdate in 'azure-arm-website' package to create a web app. But the node environment in web app is 0.10.40. Even I specify the node version in siteConfig.nodeVersion does not work.

**Comment by pierreca** [comment]
If you have a deployment problem in Azure Web Apps, how's the node SDK for IoT Hub supposed to fix that? Please file the issue either with in the azure-arm-website repository or with a support request on the portal.
