### ISSUE TITLE
Uncaught exception: NotConnectedError: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by cody-lettau** [Azure/azure-iot-sdk-node#204]
# Context
- Package Version (azure-iot-device-mqtt): 1.3.0
- OS: Debian
- Node Version: 6.2.1
- NPM Version: 5.4.2

# Description of the issue:
This occurs when attempting to open a connection with a retry mechanism. When the attempts to open continually fail (due to no internet connection), it eventually (almost exactly 4 minutes after initial attempt to open connection), it throws an error that is not caught and does not appear to be bubbled up for the consumer to catch.

# Code sample exhibiting the issue:
```
this.mqttClient.open((err) => {
                if (err) {
                    this.logger.error(`Unable to connect via MQTT: ${err.message}`);
                    deferred.reject(err.message);
                    this.connected = false;
                    return;
                }

                // Handling for successful connect below
}
```

# Console log of the issue:
```
[2018-01-19 09:52:30.962] [ERROR] application - Uncaught exception: NotConnectedError: getaddrinfo EAI_AGAIN datau-iothub.azure-devices.net:8883
    at Object.translateError (/home/clettac/dev/desie/tangerine/node_modules/azure-iot-mqtt-base/lib/mqtt_translate_error.js:48:15)
    at Mqtt._this._fsm.machina.Fsm.states.disconnected._onEnter (/home/clettac/dev/desie/tangerine/node_modules/azure-iot-device-mqtt/lib/mqtt.js:87:76)
    at _.extend.transition (/home/clettac/dev/desie/tangerine/node_modules/machina/lib/machina.js:653:28)
    at Fsm.(anonymous function) [as transition] (/home/clettac/dev/desie/tangerine/node_modules/machina/lib/machina.js:466:63)
    at /home/clettac/dev/desie/tangerine/node_modules/azure-iot-device-mqtt/lib/mqtt.js:204:52
    at MqttBase._this._fsm.machina.Fsm.states.disconnected._onEnter (/home/clettac/dev/desie/tangerine/node_modules/azure-iot-mqtt-base/lib/mqtt_base.js:39:29)
    at _.extend.transition (/home/clettac/dev/desie/tangerine/node_modules/machina/lib/machina.js:653:28)
    at Fsm.(anonymous function) [as transition] (/home/clettac/dev/desie/tangerine/node_modules/machina/lib/machina.js:466:63)
    at /home/clettac/dev/desie/tangerine/node_modules/azure-iot-mqtt-base/lib/mqtt_base.js:65:44
    at MqttClient.<anonymous> (/home/clettac/dev/desie/tangerine/node_modules/azure-iot-mqtt-base/lib/mqtt_base.js:225:17)
    at emitOne (events.js:96:13)
    at MqttClient.emit (events.js:188:7)
    at TLSSocket.handleTLSerrors (/home/clettac/dev/desie/tangerine/node_modules/mqtt/lib/connect/tls.js:26:18)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
```

**Comment by pierreca** [comment]
@cody-lettau Sorry for the super late response, I got a chance to look into it today and I do get the response through the right callback, using the [simple sample](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js) in our repository. I get the same error as you but it is bubbled up correctly through the callbacks instead of being thrown.

In your stack trace everything points to actually calling the device client callback instead of emitting the error (which would throw if there is no handler for the error event).

Can you paste a little bit more code showing us how you instantiate the device client?

**Comment by cody-lettau** [comment]
@pierreca sorry for the delay in getting back to you. I'll have time in the next few days to re-look at our implementation. I'm glad that you are seeing the error bubbled up correctly through the callbacks, so I'm guessing we haven't initiated the connection correctly. If I don't figure it out, I'll be sure to provide more detail around our implementation.

Thanks for looking into this!
