### ISSUE TITLE
AmqpError: SASL Failed: 2: undefined

### ISSUE THREAD

**Issue by Shachar1** [Azure/azure-iot-sdk-node#22]
Device that sent thousands of events suddenly started to get AmqpError: SASL Failed: 2: undefined.
Other devices are working properly.
Working on Ubuntu 14.04, node 7.3, azure-iot-device-amqp@1.1.7, azure-iot-device@1.1.7

Error: 

 { UnauthorizedError: AMQP Transport: Could not connect
    at translateError (/home/.../tcpGateway/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:52:13) at translateError (/home/.../tcpGateway/node_modules/azure-iot-device-amqp/lib/amqp_device_errors.js:20:13)
at /home/.../tcpGateway/node_modules/azure-iot-device-amqp/lib/amqp.js:43:12
at /home/.../tcpGateway/node_modules/azure-iot-amqp-base/lib/amqp.js:83:7
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
message: 'AMQP Transport: Could not connect',
amqpError:
{ AmqpError: SASL Failed: 2: undefined
at Sasl._processFrame (/home/.../tcpGateway/node_modules/amqp10/lib/sasl.js:102:21)
at Connection._processFrameEH (/home/.../tcpGateway/node_modules/amqp10/lib/sasl.js:43:49)
at emitOne (events.js:96:13)
at Connection.emit (events.js:188:7)
at Connection._receiveAny (/home/.../tcpGateway/node_modules/amqp10/lib/connection.js:426:12)
at Connection._receiveData (/home/.../tcpGateway/node_modules/amqp10/lib/connection.js:357:8)
at TlsTransport.<anonymous> (/home/.../tcpGateway/node_modules/amqp10/lib/connection.js:515:38)
at emitOne (events.js:96:13)
at TlsTransport.emit (events.js:188:7)
 at TLSSocket.<anonymous> (/home/.../tcpGateway/node_modules/amqp10/lib/transport/tls_transport.js:29:49)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at TLSSocket.Readable.push (_stream_readable.js:134:10)
at TLSWrap.onread (net.js:551:20)
name: 'AmqpAuthenticationError',
message: 'SASL Failed: 2: undefined' } }

**Comment by anthonyvercolano** [comment]
Hello Shachar1,

  Some questions:

   What type of authentication are you doing?  Are you using x509 or are you using pre-shared device key?  What is the general form of your connection string  (DO NOT REPLY with a real connection string with a key in it!!).

   When you create the device in your application, do you invoke

Client.fromConnectionString(connectionString, Protocol)

or do you invoke:

Client.fromSharedAccessSignature(sas, Protocol);

?

If you can log into a console on this device, what is the time on the device?  Has the time skewed? So while you know that it is 12:35pm local where you are, the device is saying 12:25pm.

Thank you.

**Comment by Shachar1** [comment]
Hi, 
I'm using pre-shared device key with the format - HostName=[my iot hub name];DeviceId=[the device id];SharedAccessKey=[the device key]

The code for creating the client I invoke - 
var clientFromConnectionString = require('azure-iot-device-amqp').clientFromConnectionString;
var client = clientFromConnectionString(connectionString);

The device is running on a Linux VM and it's date time is properly adjusted

Thanks.

**Comment by Shachar1** [comment]
Hi, just to add to the investigation -
I'm doing the client open only once when the app is starting - 
var clientFromConnectionString = require('azure-iot-device-amqp').clientFromConnectionString; 
var client = clientFromConnectionString(connectionString);
client.open(callback); //only once

Then for new events I'm calling - client.sendEvent();

I've noticed that if I'm getting SASL Failed: 2: undefined and then I restart my application the connection is working well. The restart calls to client.open again.

Thanks.

**Comment by anthonyvercolano** [comment]
Hello, Shachar1,

  Our last release of the node packages has a significant change to the authentication path used by the client.

  Would you be able to try your application with this release?

Thank you,
Tony
