### ISSUE TITLE
Monitor C2D message will fail when device name contains’#’

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#290]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v10.1.0
- **npm version:** 6.0.1
- **SDK version:** azure-iot-device-mqtt@1.4.1

# Code sample exhibiting the issue:
Update `<connectionString>` with connectionString of a device name which contains '#'
```javascript
'use strict';

var clientFromConnectionString = require('azure-iot-device-mqtt').clientFromConnectionString;
var Message = require('azure-iot-device').Message;
var connectionString = '<connectionString>';
var client = clientFromConnectionString(connectionString);

function printResultFor(op) {
    return function printResult(err, res) {
        if (err) console.log(op + ' error: ' + err.toString());
        if (res) console.log(op + ' status: ' + res.constructor.name);
    };
}

var connectCallback = function (err) {
    if (err) {
        console.log('Could not connect: ' + err);
    } else {
        console.log('Client connected');
        client.on('message', function (msg) {
            console.log('[Id]: ' + msg.messageId + ' [Body]: ' + msg.data);
            client.complete(msg, printResultFor('completed'));
        });
    }
};

client.open(connectCallback);
```

# Console log of the issue:
```
Client connected
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Invalid topic devices/a#/messages/devicebound/#
    at MqttClient.subscribe (d:\Try\Test\js\node_modules\mqtt\lib\client.js:457:28)
    at constructor.subscribe (d:\Try\Test\js\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:100:43)
    at constructor.handle (d:\Try\Test\js\node_modules\machina\lib\machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (d:\Try\Test\js\node_modules\machina\lib\machina.js:466:63)
    at MqttBase.subscribe (d:\Try\Test\js\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:178:19)
    at Mqtt._setupSubscription (d:\Try\Test\js\node_modules\azure-iot-device-mqtt\lib\mqtt.js:615:20)
    at constructor.enableC2D (d:\Try\Test\js\node_modules\azure-iot-device-mqtt\lib\mqtt.js:272:31)
    at constructor.handle (d:\Try\Test\js\node_modules\machina\lib\machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (d:\Try\Test\js\node_modules\machina\lib\machina.js:466:63)
    at Mqtt.enableC2D (d:\Try\Test\js\node_modules\azure-iot-device-mqtt\lib\mqtt.js:540:19)
Emitted 'error' event at:
    at d:\Try\Test\js\node_modules\azure-iot-device\lib\client.js:89:31
    at d:\Try\Test\js\node_modules\azure-iot-device\lib\client.js:501:17
    at d:\Try\Test\js\node_modules\azure-iot-common\lib\retry_operation.js:48:25
    at Immediate.<anonymous> (d:\Try\Test\js\node_modules\azure-iot-device-mqtt\lib\mqtt.js:622:13)
    at runCallback (timers.js:697:11)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by anthonyvercolano** [comment]
#288

**Comment by anthonyvercolano** [comment]
We are looking at this issue. I'll have a more definitive read on this in early June. There is a distinct possibility that including # in a device name is not supported client side over MQTT.

**Comment by pierreca** [comment]
Ran a little experiment and it seems like support for  the `#` sign needs to be reviewed with the service team. resolution might take a few more weeks.

**Comment by pierreca** [comment]
Given the inactivity around these issues I'm closing them. For all intent and purposes I'd say the `#` sign isn't supported in device ids.

**Comment by az-iot-builder-01** [comment]
@formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
