### ISSUE TITLE
azure-iothub miss lib folder in release 1.7.2

### ISSUE THREAD

**Issue by yoyo-pan** [Azure/azure-iot-sdk-node#345]
npm install any sample which contains azure-iothub will encounter this error

```
Error: Cannot find module './lib/client.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/linker/iothub-test/node_modules/azure-iothub/iothub.js:25:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Downgrade the version of azure-iothub to 1.7.1 will fix this.

**Comment by pierreca** [comment]
@yoyo-pan thanks for reporting this. it looks like the whole series of 1.7.2 packages has this issue. working on it now.
