### ISSUE TITLE
API call will fail if the local system time is set over 1 hour ago

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#365]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** Node 10
- **list of installed packages:** azure-iothub@1.7.3

# Code sample exhibiting the issue:
Set  local system time as over 1 hour ago, and then run below code

```javascript
'use strict';

var iothub = require('azure-iothub');

var connectionString = '.....';

var registry = iothub.Registry.fromConnectionString(connectionString);

// List devices
console.log('**listing devices...');
registry.list(function (err, deviceList) {
  if (err) {
    console.log(err);
    return;
  }
  deviceList.forEach(function (device) {
    var key = device.authentication ? device.authentication.symmetricKey.primaryKey : '<no primary key>';
    console.log(device.deviceId + ': ' + key);
  });
});

```
# Console log of the issue:
```
**listing devices...
{ UnauthorizedError: Unauthorized
    at Function.RestApiClient.translateError (e:\Try\Test\node_modules\azure-iothub\node_modules\azure-iot-http-base\lib\rest_api_client.js:202:25)
    at requestCallback (e:\Try\Test\node_modules\azure-iothub\node_modules\azure-iot-http-base\lib\rest_api_client.js:115:40)
    at IncomingMessage.<anonymous> (e:\Try\Test\node_modules\azure-iothub\node_modules\azure-iot-http-base\lib\http.js:117:17)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'UnauthorizedError',
  message: 'Unauthorized',
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events: { end: [Array], error: [Function], data: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-length': '161',
        'content-type': 'application/json; charset=utf-8',
        server: 'Microsoft-HTTPAPI/2.0',
        'iothub-errorcode': 'IotHubUnauthorizedAccess',
        date: 'Wed, 12 Sep 2018 06:47:42 GMT' },
     rawHeaders: 
      [ 'Content-Length',
        '161',
        'Content-Type',
        'application/json; charset=utf-8',
        'Server',
        'Microsoft-HTTPAPI/2.0',
        'iothub-errorcode',
        'IotHubUnauthorizedAccess',
        'Date',
        'Wed, 12 Sep 2018 06:47:42 GMT' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 401,
     statusMessage: 'Unauthorized',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'azure-iot-toolkit-for-mobile.azure-devices.net',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _consuming: false,
     _dumped: false,
     req: 
      ClientRequest {
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'GET /devices/?api-version=2018-06-30 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=azure-iot-toolkit-for-mobile.azure-devices.net&sig=********************************&skn=iothubowner&se=1536695260\r\nRequest-Id: 53f0dd27-8970-462c-90f6-45306ee981c3\r\nUser-Agent: azure-iothub/1.7.3\r\nHost: azure-iot-toolkit-for-mobile.azure-devices.net\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/devices/?api-version=2018-06-30',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] } },
  responseBody: '{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:b13bc0f169d64b448e609b2b136f073a-G:7-TimeStamp:09/12/2018 06:47:42"}' }
```

# Analysis
Root cause should be https://github.com/Azure/azure-iot-sdk-node/blob/734bd35f0a48b519ee4de233d1762e7ef2d4521c/common/transport/http/src/rest_api_client.ts#L111, the expiration time is set as one hour.

**Comment by anthonyvercolano** [comment]
What was the expected result?  The system has the wrong time.  As best I can recall, all authentication for service API is based upon the hub connection string which is shared key based.  As such, the final authentication token is calculated based upon the local time of the client.  Token expiration is 1 hour.

It is a best practice to keep the time on client machines relatively correct.  A few minutes either way would be fine, but 1 hour is excessive.

**Comment by az-iot-builder-01** [comment]
@formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
