### ISSUE TITLE
Error When Opening Connection

### ISSUE THREAD

**Issue by NickSchweitzer** [Azure/azure-iot-sdk-node#37]
# Context
Running on an Intel Edison
Code can be found in this GitHub repository:
https://github.com/NickSchweitzer/SumpPumpMonitor/tree/master/Edison

# Description of the issue:
Cannot successfully open a connection to the IOT Hub Client in order to get a Device Twin using MQTT

# Code sample exhibiting the issue:
https://github.com/NickSchweitzer/SumpPumpMonitor/blob/master/Edison/SumpPump.ts

# Console log of the issue:
/home/root/SumpPumpEdison/node_modules/azure-iot-device-mqtt/lib/mqtt.js:221
  if (!util.isString(method) || !util.isString(resource))
            ^
TypeError: Object #<Object> has no method 'isString'
    at Mqtt.sendTwinRequest (/home/root/SumpPumpEdison/node_modules/azure-iot-device-mqtt/lib/mqtt.js:221:13)
    at Twin._sendTwinRequest (/home/root/SumpPumpEdison/node_modules/azure-iot-device/lib/twin.js:220:27)
    at Twin._getPropertiesFromService (/home/root/SumpPumpEdison/node_modules/azure-iot-device/lib/twin.js:273:8)
    at /home/root/SumpPumpEdison/node_modules/azure-iot-device/lib/twin.js:97:16
    at cleanupAndReturn (/home/root/SumpPumpEdison/node_modules/azure-iot-device/lib/twin.js:160:5)
    at MqttTwinReceiver.handleSubscribed (/home/root/SumpPumpEdison/node_modules/azure-iot-device/lib/twin.js:137:9)
    at MqttTwinReceiver.emit (events.js:95:17)
    at /home/root/SumpPumpEdison/node_modules/azure-iot-device-mqtt/lib/mqtt-twin-receiver.js:88:18
    at /home/root/SumpPumpEdison/node_modules/azure-iot-device-mqtt/node_modules/mqtt/lib/client.js:867:9
    at Store.del (/home/root/SumpPumpEdison/node_modules/azure-iot-device-mqtt/node_modules/mqtt/lib/store.js:76:5)

**Comment by NickSchweitzer** [comment]
Further version information...
Running Yocto v1.7.3
Node v0.10.38

**Comment by NickSchweitzer** [comment]
Closing issue - I upgraded the firmware on the Edison and am now using latest Node (v4.4.3), and the issue no longer occurs.
