### ISSUE TITLE
NotConnectedError: mqtt.js returned client disconnecting error

### ISSUE THREAD

**Issue by rahulunlimited** [Azure/azure-iot-sdk-node#458]
I have setup a Raspberry Pi 3 B+ device connected to Azure S1 IoT Hub over wifi. I have noticed after approximate 45 minutes the connection always breaks and reports the error NotConnectedError: mqtt.js returned client disconnecting error.
The only difference in my code is I use nohup command to initiaite the node.js so that the application runs even when the terminal window is closed.
nohup sudo node index.js 'HostName=vlriothub.azure-devices.net;DeviceId=raspberrypisensor;SharedAccessKey=XXXXXXXXX' >> server.log 2>&1 < /dev/null &

I also updated the package.json file reading the previously opened issues
"dependencies": {
"az-iot-bi": "^0.1.18",
"azure-iot-device": "1.7.4",
"azure-iot-device-mqtt": "1.7.4",
"bme280-sensor": "^0.1.6",
"node-wiring-pi": ">=2.1.1"
},

However, the error is still occurring.

The complete error message
home/pi/iot-hub-node-raspberrypi-client-app/node_modules/az-iot-bi/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
throw error;
^
NotConnectedError: mqtt.js returned client disconnecting error
at translateError (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/lib/mqtt-translate-error.js:25:11)
at MqttTwinReceiver._handleError (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/lib/mqtt-twin-receiver.js:201:42)
at /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/lib/mqtt-twin-receiver.js:64:18
at MqttClient._checkDisconnecting (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/node_modules/mqtt/lib/client.js:314:7)
at MqttClient.subscribe (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/node_modules/mqtt/lib/client.js:423:12)
at /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt/lib/mqtt-twin-receiver.js:62:22
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by anthonyvercolano** [comment]
This seems like you have a somewhat older client here.  The stack trace includes mqtt-twin-receiver.  That hasn't been around for quite some time, so I'm thinking you are not actually on 1.7.4?

Using mqtt with a shared key WILL always disconnect after around 45 minutes because the SAS authentication will be expiring shortly.  While I should talk with some of the other SDK members, I'm surprised that the disconnect and automatic re-connect that happens at around the 45 minute mark.

Is it possible to try this with a clean install of the current SDK?

**Comment by anthonyvercolano** [comment]
Also do an npm ls

**Comment by rahulunlimited** [comment]
I updated the npm to version 2.18.8 and rerun the code. It failed again after around 45 minutes.

Error message
/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/az-iot-bi/node_modules                          /applicationinsights/AutoCollection/Exceptions.js:27
                        throw error;
                        ^
NotConnectedError: mqtt.js returned client disconnecting error
    at translateError (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules                          /azure-iot-device-mqtt/lib/mqtt-translate-error.js:25:11)
    at MqttTwinReceiver._handleError (/home/pi/iot-hub-node-raspberrypi-client-a                          pp/node_modules/azure-iot-device-mqtt/lib/mqtt-twin-receiver.js:201:42)
    at /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-devic                          e-mqtt/lib/mqtt-twin-receiver.js:64:18
    at MqttClient._checkDisconnecting (/home/pi/iot-hub-node-raspberrypi-client-                          app/node_modules/azure-iot-device-mqtt/node_modules/mqtt/lib/client.js:314:7)
    at MqttClient.subscribe (/home/pi/iot-hub-node-raspberrypi-client-app/node_m                          odules/azure-iot-device-mqtt/node_modules/mqtt/lib/client.js:423:12)
    at /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-devic                          e-mqtt/lib/mqtt-twin-receiver.js:62:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by rahulunlimited** [comment]
Output for npm ls.

(node:1491) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
iot-hub-node-raspberrypi-client-app@1.0.0 /home/pi/iot-hub-node-raspberrypi-client-app
├─┬ az-iot-bi@0.1.20
│ ├── applicationinsights@0.17.2
│ ├─┬ async@2.6.1
│ │ └── lodash@4.17.11
│ ├─┬ execa@0.5.1
│ │ ├─┬ cross-spawn@4.0.2
│ │ │ ├─┬ lru-cache@4.1.5
│ │ │ │ ├── pseudomap@1.0.2
│ │ │ │ └── yallist@2.1.2
│ │ │ └─┬ which@1.3.1
│ │ │   └── isexe@2.0.0
│ │ ├─┬ get-stream@2.3.1
│ │ │ ├── object-assign@4.1.1
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├── is-stream@1.1.0
│ │ ├─┬ npm-run-path@2.0.2
│ │ │ └── path-key@2.0.1
│ │ ├── p-finally@1.0.0
│ │ ├── signal-exit@3.0.2
│ │ └── strip-eof@1.0.0
│ ├─┬ getos@2.8.4
│ │ └─┬ async@2.1.4
│ │   └── lodash@4.17.11
│ ├── macaddress@0.2.9
│ ├── pkginfo@0.4.1
│ ├── readline-sync@1.4.9
│ └─┬ user-home@2.0.0
│   └── os-homedir@1.0.2
├─┬ azure-iot-device@1.1.7 invalid
│ ├─┬ azure-iot-common@1.1.5
│ │ └── crypto@0.0.3
│ ├── azure-iot-http-base@1.1.5
│ ├─┬ azure-storage@2.10.2
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@3.0.2
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ └── safe-buffer@5.1.2
│ │ │ └── inherits@2.0.3
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.88.0
│ │ │ ├── aws-sign2@0.7.0
│ │ │ ├── aws4@1.8.0
│ │ │ ├── caseless@0.12.0
│ │ │ ├─┬ combined-stream@1.0.7
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.3.3
│ │ │ │ └── asynckit@0.4.0
│ │ │ ├─┬ har-validator@5.1.3
│ │ │ │ ├─┬ ajv@6.6.2
│ │ │ │ │ ├── fast-deep-equal@2.0.1
│ │ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ │ ├── json-schema-traverse@0.4.1
│ │ │ │ │ └─┬ uri-js@4.2.2
│ │ │ │ │   └── punycode@2.1.1
│ │ │ │ └── har-schema@2.0.0
│ │ │ ├─┬ http-signature@1.2.0
│ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   └── core-util-is@1.0.2
│ │ │ │ └─┬ sshpk@1.16.0
│ │ │ │   ├── asn1@0.2.4
│ │ │ │   ├── bcrypt-pbkdf@1.0.2
│ │ │ │   ├── dashdash@1.14.1
│ │ │ │   ├── ecc-jsbn@0.1.2
│ │ │ │   ├── getpass@0.1.7
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   ├── safer-buffer@2.1.2
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.21
│ │ │ │ └── mime-db@1.37.0
│ │ │ ├── oauth-sign@0.9.0
│ │ │ ├── performance-now@2.1.0
│ │ │ ├── qs@6.5.2
│ │ │ ├── safe-buffer@5.1.2
│ │ │ ├─┬ tough-cookie@2.4.3
│ │ │ │ ├── psl@1.1.31
│ │ │ │ └── punycode@1.4.1
│ │ │ └── tunnel-agent@0.6.0
│ │ ├── underscore@1.8.3
│ │ ├── uuid@3.3.2
│ │ ├── validator@9.4.1
│ │ ├─┬ xml2js@0.2.8
│ │ │ └── sax@0.5.8
│ │ └── xmlbuilder@9.0.7
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── es5-shim@4.5.12
│ ├── lodash@4.17.11
│ ├─┬ machina@2.0.2
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-mqtt@1.1.7 invalid
│ ├─┬ azure-iot-common@1.1.5
│ │ └── crypto@0.0.3
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── es5-shim@4.5.12
│ └─┬ mqtt@1.14.1
│   ├─┬ commist@1.0.0
│   │ └── leven@1.0.2
│   ├─┬ concat-stream@1.6.2
│   │ ├── buffer-from@1.1.1
│   │ ├─┬ readable-stream@2.3.6
│   │ │ ├── core-util-is@1.0.2
│   │ │ ├── isarray@1.0.0
│   │ │ ├── process-nextick-args@2.0.0
│   │ │ ├── safe-buffer@5.1.2
│   │ │ ├── string_decoder@1.1.1
│   │ │ └── util-deprecate@1.0.2
│   │ └── typedarray@0.0.6
│   ├─┬ end-of-stream@1.4.1
│   │ └─┬ once@1.4.0
│   │   └── wrappy@1.0.2
│   ├─┬ help-me@1.1.0
│   │ ├── callback-stream@1.1.0
│   │ ├─┬ glob-stream@6.1.0
│   │ │ ├── extend@3.0.2
│   │ │ ├─┬ glob@7.1.3
│   │ │ │ ├── fs.realpath@1.0.0
│   │ │ │ ├─┬ inflight@1.0.6
│   │ │ │ │ └── wrappy@1.0.2
│   │ │ │ ├─┬ minimatch@3.0.4
│   │ │ │ │ └─┬ brace-expansion@1.1.11
│   │ │ │ │   ├── balanced-match@1.0.0
│   │ │ │ │   └── concat-map@0.0.1
│   │ │ │ ├─┬ once@1.4.0
│   │ │ │ │ └── wrappy@1.0.2
│   │ │ │ └── path-is-absolute@1.0.1
│   │ │ ├─┬ glob-parent@3.1.0
│   │ │ │ ├─┬ is-glob@3.1.0
│   │ │ │ │ └── is-extglob@2.1.1
│   │ │ │ └── path-dirname@1.0.2
│   │ │ ├── is-negated-glob@1.0.0
│   │ │ ├── ordered-read-streams@1.0.1
│   │ │ ├─┬ pumpify@1.5.1
│   │ │ │ ├─┬ duplexify@3.6.1
│   │ │ │ │ └── stream-shift@1.0.0
│   │ │ │ └─┬ pump@2.0.1
│   │ │ │   └─┬ once@1.4.0
│   │ │ │     └── wrappy@1.0.2
│   │ │ ├─┬ readable-stream@2.3.6
│   │ │ │ ├── core-util-is@1.0.2
│   │ │ │ ├── isarray@1.0.0
│   │ │ │ ├── process-nextick-args@2.0.0
│   │ │ │ ├── safe-buffer@5.1.2
│   │ │ │ ├── string_decoder@1.1.1
│   │ │ │ └── util-deprecate@1.0.2
│   │ │ ├── remove-trailing-separator@1.1.0
│   │ │ ├─┬ to-absolute-glob@2.0.2
│   │ │ │ └─┬ is-absolute@1.0.0
│   │ │ │   ├─┬ is-relative@1.0.0
│   │ │ │   │ └─┬ is-unc-path@1.0.0
│   │ │ │   │   └── unc-path-regex@0.1.2
│   │ │ │   └── is-windows@1.0.2
│   │ │ └─┬ unique-stream@2.3.1
│   │ │   ├── json-stable-stringify-without-jsonify@1.0.1
│   │ │   └── through2-filter@3.0.0
│   │ └─┬ through2@2.0.5
│   │   └─┬ readable-stream@2.3.6
│   │     ├── core-util-is@1.0.2
│   │     ├── isarray@1.0.0
│   │     ├── process-nextick-args@2.0.0
│   │     ├── safe-buffer@5.1.2
│   │     ├── string_decoder@1.1.1
│   │     └── util-deprecate@1.0.2
│   ├── inherits@2.0.3
│   ├── minimist@1.2.0
│   ├─┬ mqtt-connection@2.1.1
│   │ ├── reduplexer@1.1.0
│   │ └── through2@0.6.5
│   ├─┬ mqtt-packet@3.5.0
│   │ └─┬ bl@1.2.2
│   │   ├─┬ readable-stream@2.3.6
│   │   │ ├── core-util-is@1.0.2
│   │   │ ├── isarray@1.0.0
│   │   │ ├── process-nextick-args@2.0.0
│   │   │ ├── string_decoder@1.1.1
│   │   │ └── util-deprecate@1.0.2
│   │   └── safe-buffer@5.1.2
│   ├─┬ pump@1.0.3
│   │ └─┬ once@1.4.0
│   │   └── wrappy@1.0.2
│   ├─┬ readable-stream@1.0.34
│   │ ├── core-util-is@1.0.2
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   ├── reinterval@1.1.0
│   ├─┬ split2@2.2.0
│   │ └─┬ through2@2.0.5
│   │   └─┬ readable-stream@2.3.6
│   │     ├── core-util-is@1.0.2
│   │     ├── isarray@1.0.0
│   │     ├── process-nextick-args@2.0.0
│   │     ├── safe-buffer@5.1.2
│   │     ├── string_decoder@1.1.1
│   │     └── util-deprecate@1.0.2
│   ├─┬ websocket-stream@3.3.3
│   │ ├─┬ duplexify@3.6.1
│   │ │ ├─┬ readable-stream@2.3.6
│   │ │ │ ├── core-util-is@1.0.2
│   │ │ │ ├── isarray@1.0.0
│   │ │ │ ├── process-nextick-args@2.0.0
│   │ │ │ ├── safe-buffer@5.1.2
│   │ │ │ ├── string_decoder@1.1.1
│   │ │ │ └── util-deprecate@1.0.2
│   │ │ └── stream-shift@1.0.0
│   │ ├─┬ through2@2.0.5
│   │ │ └─┬ readable-stream@2.3.6
│   │ │   ├── core-util-is@1.0.2
│   │ │   ├── isarray@1.0.0
│   │ │   ├── process-nextick-args@2.0.0
│   │ │   ├── safe-buffer@5.1.2
│   │ │   ├── string_decoder@1.1.1
│   │ │   └── util-deprecate@1.0.2
│   │ └─┬ ws@1.1.5
│   │   ├── options@0.0.6
│   │   └── ultron@1.0.2
│   └── xtend@4.0.1
├─┬ bme280-sensor@0.1.6
│ └─┬ i2c-bus@1.2.5
│   ├── bindings@1.3.1
│   └── nan@2.8.0
├─┬ eslint@3.19.0
│ ├─┬ babel-code-frame@6.26.0
│ │ └── js-tokens@3.0.2
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.6.2
│ │ ├── buffer-from@1.1.1
│ │ ├── inherits@2.0.3
│ │ ├─┬ readable-stream@2.3.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@2.0.0
│ │ │ ├── safe-buffer@5.1.2
│ │ │ ├── string_decoder@1.1.1
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── doctrine@2.1.0
│ ├─┬ escope@3.6.0
│ │ ├─┬ es6-map@0.1.5
│ │ │ ├── d@1.0.0
│ │ │ ├─┬ es5-ext@0.10.46
│ │ │ │ └── next-tick@1.0.0
│ │ │ ├── es6-iterator@2.0.3
│ │ │ ├── es6-set@0.1.5
│ │ │ ├── es6-symbol@3.1.1
│ │ │ └── event-emitter@0.3.5
│ │ ├─┬ es6-weak-map@2.0.2
│ │ │ ├── d@1.0.0
│ │ │ ├─┬ es5-ext@0.10.46
│ │ │ │ └── next-tick@1.0.0
│ │ │ ├── es6-iterator@2.0.3
│ │ │ └── es6-symbol@3.1.1
│ │ └── esrecurse@4.2.1
│ ├─┬ espree@3.5.4
│ │ ├── acorn@5.7.3
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├── esquery@1.0.1
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@2.0.0
│ │ ├─┬ flat-cache@1.3.4
│ │ │ ├── circular-json@0.3.3
│ │ │ ├── graceful-fs@4.1.15
│ │ │ ├── rimraf@2.6.3
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.1.1
│ ├─┬ glob@7.1.3
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.11
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2
│ │ └── path-is-absolute@1.0.1
│ ├── globals@9.18.0
│ ├── ignore@3.3.10
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@0.12.0
│ │ ├── ansi-escapes@1.4.0
│ │ ├── ansi-regex@2.1.1
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.2.0
│ │ ├─┬ figures@1.7.0
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ └── object-assign@4.1.1
│ │ ├─┬ readline2@1.0.1
│ │ │ ├── code-point-at@1.1.0
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ └── number-is-nan@1.0.1
│ │ │ └── mute-stream@0.0.5
│ │ ├─┬ run-async@0.1.0
│ │ │ └─┬ once@1.4.0
│ │ │   └── wrappy@1.0.2
│ │ ├── rx-lite@3.1.2
│ │ ├─┬ string-width@1.0.2
│ │ │ ├── code-point-at@1.1.0
│ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │   └── number-is-nan@1.0.1
│ │ ├── strip-ansi@3.0.1
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.19.0
│ │ ├─┬ generate-function@2.3.1
│ │ │ └── is-property@1.0.2
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── is-my-ip-valid@1.0.0
│ │ ├── jsonpointer@4.0.1
│ │ └── xtend@4.0.1
│ ├── is-resolvable@1.1.0
│ ├─┬ js-yaml@3.12.0
│ │ ├─┬ argparse@1.0.10
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.1
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├── lodash@4.17.11
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── natural-compare@1.4.0
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@2.0.6
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.2
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.2
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├─┬ shelljs@0.7.8
│ │ ├── interpret@1.2.0
│ │ └─┬ rechoir@0.6.2
│ │   └─┬ resolve@1.9.0
│ │     └── path-parse@1.0.6
│ ├── strip-bom@3.0.0
│ ├── strip-json-comments@2.0.1
│ ├─┬ table@3.8.3
│ │ ├─┬ ajv@4.11.8
│ │ │ └── co@4.6.0
│ │ ├── ajv-keywords@1.5.1
│ │ ├── slice-ansi@0.0.4
│ │ └─┬ string-width@2.1.1
│ │   ├── is-fullwidth-code-point@2.0.0
│ │   └─┬ strip-ansi@4.0.0
│ │     └── ansi-regex@3.0.0
│ ├── text-table@0.2.0
│ └─┬ user-home@2.0.0
│   └── os-homedir@1.0.2
└─┬ node-wiring-pi@0.0.4 invalid
  ├── bindings@1.2.1
  └── nan@2.12.1

npm ERR! invalid: azure-iot-device@1.1.7 /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device
npm ERR! invalid: azure-iot-device-mqtt@1.1.7 /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device-mqtt
npm ERR! invalid: node-wiring-pi@0.0.4 /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi
npm ERR! not ok code 0

**Comment by anthonyvercolano** [comment]
The versions of the SDK that you are working with are at least 18 months old.  I would urge upgrading to the latest SDK.  If the problem still persists then at least we have something we can generate a fix for.

**Comment by rahulunlimited** [comment]
Can you please help me with the link to the SDK to be upgraded

**Comment by anthonyvercolano** [comment]
I personally would suggest you move the versions in your package.json to 1.8.3 for the azure-iot-sdk packages.

Also, since I have a tendency to hit things with big hammers, I might remove the node_modules directory and recreate it with a npm install.   However, that's up to you.  Hopefully the package.json file in your directory is up to date with all your package installs during your development.

**Comment by rahulunlimited** [comment]
Thanks Anthony for your suggestion. After updating the SDKs the solution seems to be running fine for the last 9 hour without interruption.
