### ISSUE TITLE
Connection String Error in build.cmd for verifying development environment installation

### ISSUE THREAD

**Issue by albhardy** [Azure/azure-iot-sdk-node#5]
# Context
- **OS and version used:** Windows 10 
- **Node.js version:** v6.4.0 
- **npm version:** 3.10.3 

# Description of the issue:
As highlighted in [preparing env article](https://github.com/Azure/azure-iot-sdk-node/blob/master/doc/node-devbox-setup.md), I encountered following error after running `build\build.cmd` after executing `.\build\dev-setup.cmd`:

    
    if (!(key in dict)) throw new ArgumentError(err + key);
                       ^
    Error
    at new ArgumentError (D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\common\core\lib\errors.js:14:17)
    at D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\common\core\lib\connection_string.js:21:31
    at Array.forEach (native)
    at Function.parse (D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\common\core\lib\connection_string.js:20:18)
    at Object.parse (D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\service\lib\connection_string.js:12:17)
    at Function.fromConnectionString (D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\service\lib\registry.js:61:29)
    at Object.<anonymous> (D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\build\tools\create_device_certs.js:62:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

It ends with following message:

    Could Not Find D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\x509device-node-13158-cert.pe
    Could Not Find D:\DEV\AZURE\IOTHUB\azure-iot-sdk-node-master\x509device-node-13158-key.pem

I'm trying to figure out if there's issue on my development environment as I could not execute send message in [Getting Started with IOT](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted) Tutorial

    > node SimulatedDevice.js
    Could not connect: connect ETIMEDOUT 40.83.177.42:8883

However I manage to send message using HTTP instead of MQTT as transport protocol. Am I missing something here?

# Console log of the issue:  

![image](https://cloud.githubusercontent.com/assets/1732018/21379368/6b77c858-c788-11e6-88b6-6159f620c3bd.png)

**Comment by albhardy** [comment]
Adding this on `build.cmd` seems solve the problem (though the error still appear for --integration-tests)

    set IOTHUB_CONNECTION_STRING="HostName=nxxxx;SharedAccessKeyName=xxxxx;SharedAccessKey=xxxx"

Also, need to ensure openssl is in System PATH

**Comment by pierreca** [comment]
Thanks for pointing this out! the instructions were outdated. I updated them: 
https://github.com/Azure/azure-iot-sdk-node/commit/36165cb08443724810073c3cdbf5bb05a2018814
