### ISSUE TITLE
lack of support for unix domain sockets (affects module on Windows containers using IoT Edge)

### ISSUE THREAD

**Issue by Griffrez** [Azure/azure-iot-sdk-node#500]
# Context
- **OS and version used:** Windows 10 1809
- **Node.js version:** v8.15.0
- **npm version:** 6.4.1
- **list of installed packages:**
```
+-- azure-iot-device@1.9.3
| +-- azure-iot-common@1.9.3
| | `-- getos@3.1.1
| |   `-- async@2.6.1
| |     `-- lodash@4.17.11 deduped
| +-- azure-iot-http-base@1.9.3
| | +-- azure-iot-common@1.9.3 deduped
| | +-- debug@3.2.6 deduped
| | `-- uuid@3.3.2 deduped
| +-- azure-storage@2.10.2
| | +-- browserify-mime@1.2.9
| | +-- extend@3.0.2
| | +-- json-edm-parser@0.1.2
| | | `-- jsonparse@1.2.0
| | +-- md5.js@1.3.4
| | | +-- hash-base@3.0.4
| | | | +-- inherits@2.0.3 deduped
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- inherits@2.0.3
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- inherits@2.0.3 deduped
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | +-- request@2.88.0
| | | +-- aws-sign2@0.7.0
| | | +-- aws4@1.8.0
| | | +-- caseless@0.12.0
| | | +-- combined-stream@1.0.7
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.2 deduped
| | | +-- forever-agent@0.6.1
| | | +-- form-data@2.3.3
| | | | +-- asynckit@0.4.0
| | | | +-- combined-stream@1.0.7 deduped
| | | | `-- mime-types@2.1.22 deduped
| | | +-- har-validator@5.1.3
| | | | +-- ajv@6.9.2
| | | | | +-- fast-deep-equal@2.0.1
| | | | | +-- fast-json-stable-stringify@2.0.0
| | | | | +-- json-schema-traverse@0.4.1
| | | | | `-- uri-js@4.2.2
| | | | |   `-- punycode@2.1.1
| | | | `-- har-schema@2.0.0
| | | +-- http-signature@1.2.0
| | | | +-- assert-plus@1.0.0
| | | | +-- jsprim@1.4.1
| | | | | +-- assert-plus@1.0.0 deduped
| | | | | +-- extsprintf@1.3.0
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.10.0
| | | | |   +-- assert-plus@1.0.0 deduped
| | | | |   +-- core-util-is@1.0.2 deduped
| | | | |   `-- extsprintf@1.3.0 deduped
| | | | `-- sshpk@1.16.1
| | | |   +-- asn1@0.2.4
| | | |   | `-- safer-buffer@2.1.2 deduped
| | | |   +-- assert-plus@1.0.0 deduped
| | | |   +-- bcrypt-pbkdf@1.0.2
| | | |   | `-- tweetnacl@0.14.5 deduped
| | | |   +-- dashdash@1.14.1
| | | |   | `-- assert-plus@1.0.0 deduped
| | | |   +-- ecc-jsbn@0.1.2
| | | |   | +-- jsbn@0.1.1 deduped
| | | |   | `-- safer-buffer@2.1.2 deduped
| | | |   +-- getpass@0.1.7
| | | |   | `-- assert-plus@1.0.0 deduped
| | | |   +-- jsbn@0.1.1
| | | |   +-- safer-buffer@2.1.2
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.22
| | | | `-- mime-db@1.38.0
| | | +-- oauth-sign@0.9.0
| | | +-- performance-now@2.1.0
| | | +-- qs@6.5.2
| | | +-- safe-buffer@5.1.2
| | | +-- tough-cookie@2.4.3
| | | | +-- psl@1.1.31
| | | | `-- punycode@1.4.1
| | | +-- tunnel-agent@0.6.0
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- uuid@3.3.2 deduped
| | +-- underscore@1.8.3
| | +-- uuid@3.3.2 deduped
| | +-- validator@9.4.1
| | +-- xml2js@0.2.8
| | | `-- sax@0.5.8
| | `-- xmlbuilder@9.0.7
| +-- debug@3.2.6
| | `-- ms@2.1.1
| +-- lodash@4.17.11
| +-- machina@4.0.2
| | `-- lodash@4.17.11 deduped
| `-- traverse@0.6.6
`-- azure-iot-device-mqtt@1.9.3
  +-- azure-iot-common@1.9.3 deduped
  +-- azure-iot-device@1.9.3 deduped
  +-- azure-iot-mqtt-base@1.9.3
  | +-- azure-iot-common@1.9.3 deduped
  | +-- debug@3.2.6 deduped
  | +-- machina@4.0.2 deduped
  | `-- mqtt@2.18.8
  |   +-- commist@1.0.0
  |   | +-- leven@1.0.2
  |   | `-- minimist@1.2.0 deduped
  |   +-- concat-stream@1.6.2
  |   | +-- buffer-from@1.1.1
  |   | +-- inherits@2.0.3 deduped
  |   | +-- readable-stream@2.3.6
  |   | | +-- core-util-is@1.0.2 deduped
  |   | | +-- inherits@2.0.3 deduped
  |   | | +-- isarray@1.0.0 deduped
  |   | | +-- process-nextick-args@2.0.0
  |   | | +-- safe-buffer@5.1.2 deduped
  |   | | +-- string_decoder@1.1.1
  |   | | | `-- safe-buffer@5.1.2 deduped
  |   | | `-- util-deprecate@1.0.2 deduped
  |   | `-- typedarray@0.0.6
  |   +-- end-of-stream@1.4.1
  |   | `-- once@1.4.0
  |   |   `-- wrappy@1.0.2
  |   +-- es6-map@0.1.5
  |   | +-- d@1.0.0
  |   | | `-- es5-ext@0.10.48 deduped
  |   | +-- es5-ext@0.10.48
  |   | | +-- es6-iterator@2.0.3 deduped
  |   | | +-- es6-symbol@3.1.1 deduped
  |   | | `-- next-tick@1.0.0
  |   | +-- es6-iterator@2.0.3
  |   | | +-- d@1.0.0 deduped
  |   | | +-- es5-ext@0.10.48 deduped
  |   | | `-- es6-symbol@3.1.1 deduped
  |   | +-- es6-set@0.1.5
  |   | | +-- d@1.0.0 deduped
  |   | | +-- es5-ext@0.10.48 deduped
  |   | | +-- es6-iterator@2.0.3 deduped
  |   | | +-- es6-symbol@3.1.1 deduped
  |   | | `-- event-emitter@0.3.5 deduped
  |   | +-- es6-symbol@3.1.1
  |   | | +-- d@1.0.0 deduped
  |   | | `-- es5-ext@0.10.48 deduped
  |   | `-- event-emitter@0.3.5
  |   |   +-- d@1.0.0 deduped
  |   |   `-- es5-ext@0.10.48 deduped
  |   +-- help-me@1.1.0
  |   | +-- callback-stream@1.1.0
  |   | | +-- inherits@2.0.3 deduped
  |   | | `-- readable-stream@2.0.6 deduped
  |   | +-- glob-stream@6.1.0
  |   | | +-- extend@3.0.2 deduped
  |   | | +-- glob@7.1.3
  |   | | | +-- fs.realpath@1.0.0
  |   | | | +-- inflight@1.0.6
  |   | | | | +-- once@1.4.0 deduped
  |   | | | | `-- wrappy@1.0.2 deduped
  |   | | | +-- inherits@2.0.3 deduped
  |   | | | +-- minimatch@3.0.4
  |   | | | | `-- brace-expansion@1.1.11
  |   | | | |   +-- balanced-match@1.0.0
  |   | | | |   `-- concat-map@0.0.1
  |   | | | +-- once@1.4.0 deduped
  |   | | | `-- path-is-absolute@1.0.1
  |   | | +-- glob-parent@3.1.0
  |   | | | +-- is-glob@3.1.0
  |   | | | | `-- is-extglob@2.1.1
  |   | | | `-- path-dirname@1.0.2
  |   | | +-- is-negated-glob@1.0.0
  |   | | +-- ordered-read-streams@1.0.1
  |   | | | `-- readable-stream@2.0.6 deduped
  |   | | +-- pumpify@1.5.1
  |   | | | +-- duplexify@3.7.1 deduped
  |   | | | +-- inherits@2.0.3 deduped
  |   | | | `-- pump@2.0.1
  |   | | |   +-- end-of-stream@1.4.1 deduped
  |   | | |   `-- once@1.4.0 deduped
  |   | | +-- readable-stream@2.3.6
  |   | | | +-- core-util-is@1.0.2 deduped
  |   | | | +-- inherits@2.0.3 deduped
  |   | | | +-- isarray@1.0.0 deduped
  |   | | | +-- process-nextick-args@2.0.0
  |   | | | +-- safe-buffer@5.1.2 deduped
  |   | | | +-- string_decoder@1.1.1
  |   | | | | `-- safe-buffer@5.1.2 deduped
  |   | | | `-- util-deprecate@1.0.2 deduped
  |   | | +-- remove-trailing-separator@1.1.0
  |   | | +-- to-absolute-glob@2.0.2
  |   | | | +-- is-absolute@1.0.0
  |   | | | | +-- is-relative@1.0.0
  |   | | | | | `-- is-unc-path@1.0.0
  |   | | | | |   `-- unc-path-regex@0.1.2
  |   | | | | `-- is-windows@1.0.2
  |   | | | `-- is-negated-glob@1.0.0 deduped
  |   | | `-- unique-stream@2.3.1
  |   | |   +-- json-stable-stringify-without-jsonify@1.0.1
  |   | |   `-- through2-filter@3.0.0
  |   | |     +-- through2@2.0.5 deduped
  |   | |     `-- xtend@4.0.1 deduped
  |   | +-- through2@2.0.5
  |   | | +-- readable-stream@2.3.6
  |   | | | +-- core-util-is@1.0.2 deduped
  |   | | | +-- inherits@2.0.3 deduped
  |   | | | +-- isarray@1.0.0 deduped
  |   | | | +-- process-nextick-args@2.0.0
  |   | | | +-- safe-buffer@5.1.2 deduped
  |   | | | +-- string_decoder@1.1.1
  |   | | | | `-- safe-buffer@5.1.2 deduped
  |   | | | `-- util-deprecate@1.0.2 deduped
  |   | | `-- xtend@4.0.1 deduped
  |   | `-- xtend@4.0.1 deduped
  |   +-- inherits@2.0.3 deduped
  |   +-- minimist@1.2.0
  |   +-- mqtt-packet@5.6.0
  |   | +-- bl@1.2.2
  |   | | +-- readable-stream@2.3.6
  |   | | | +-- core-util-is@1.0.2 deduped
  |   | | | +-- inherits@2.0.3 deduped
  |   | | | +-- isarray@1.0.0 deduped
  |   | | | +-- process-nextick-args@2.0.0
  |   | | | +-- safe-buffer@5.1.2 deduped
  |   | | | +-- string_decoder@1.1.1
  |   | | | | `-- safe-buffer@5.1.2 deduped
  |   | | | `-- util-deprecate@1.0.2 deduped
  |   | | `-- safe-buffer@5.1.2 deduped
  |   | +-- inherits@2.0.3 deduped
  |   | +-- process-nextick-args@2.0.0
  |   | `-- safe-buffer@5.1.2 deduped
  |   +-- pump@3.0.0
  |   | +-- end-of-stream@1.4.1 deduped
  |   | `-- once@1.4.0 deduped
  |   +-- readable-stream@2.3.6
  |   | +-- core-util-is@1.0.2 deduped
  |   | +-- inherits@2.0.3 deduped
  |   | +-- isarray@1.0.0 deduped
  |   | +-- process-nextick-args@2.0.0
  |   | +-- safe-buffer@5.1.2 deduped
  |   | +-- string_decoder@1.1.1
  |   | | `-- safe-buffer@5.1.2 deduped
  |   | `-- util-deprecate@1.0.2 deduped
  |   +-- reinterval@1.1.0
  |   +-- split2@2.2.0
  |   | `-- through2@2.0.5 deduped
  |   +-- websocket-stream@5.1.2
  |   | +-- duplexify@3.7.1
  |   | | +-- end-of-stream@1.4.1 deduped
  |   | | +-- inherits@2.0.3 deduped
  |   | | +-- readable-stream@2.0.6 deduped
  |   | | `-- stream-shift@1.0.0
  |   | +-- inherits@2.0.3 deduped
  |   | +-- readable-stream@2.3.6
  |   | | +-- core-util-is@1.0.2 deduped
  |   | | +-- inherits@2.0.3 deduped
  |   | | +-- isarray@1.0.0 deduped
  |   | | +-- process-nextick-args@2.0.0
  |   | | +-- safe-buffer@5.1.2 deduped
  |   | | +-- string_decoder@1.1.1
  |   | | | `-- safe-buffer@5.1.2 deduped
  |   | | `-- util-deprecate@1.0.2 deduped
  |   | +-- safe-buffer@5.1.2 deduped
  |   | +-- ws@3.3.3
  |   | | +-- async-limiter@1.0.0
  |   | | +-- safe-buffer@5.1.2 deduped
  |   | | `-- ultron@1.1.1
  |   | `-- xtend@4.0.1 deduped
  |   `-- xtend@4.0.1
  +-- debug@3.2.6 deduped
  +-- machina@4.0.2 deduped
  `-- uuid@3.3.2
```

# Description of the issue:
I'm attempting to use Node.js modules using Windows as the underlying host operating system.

I've used the example generated by Azure IoT Edge Visual Studio Code extension for Node.js modules.

I've successfully booted the module under the IoT Edge environment, but now I have an issue where I get the following error when running ModuleClient.fromEnvironment:
```
2019-03-01T09:51:12.431Z azure-iot-http-base.RestApiClient sending GET call to /trust-bundle?api-version=2018-06-28
2019-03-01T09:51:12.437Z azure-iot-http-base.RestApiClient GET call to /trust-bundle?api-version=2018-06-28 returned Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
Debugger attached.
C:\app\app.js:9
    throw err;
    ^

Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

I noticed that there's a forward slash at the beginning of the path and that is probably part of the problem.

The IoT Edge runtime sets the environmental variable IOTEDGE_WORKLOADURI to `unix:///C:/ProgramData/iotedge/workload/sock` which causes the URL parser to interpret the pathname as `/C:/ProgramData/iotedge/workload/sock`.

Using a debugger to manually change the received pathname to  `C:/ProgramData/iotedge/workload/sock` creates this error message instead:
```
2019-03-01T09:57:38.893Z azure-iot-http-base.RestApiClient sending GET call to /trust-bundle?api-version=2018-06-28
2019-03-01T09:57:38.903Z azure-iot-http-base.RestApiClient GET call to /trust-bundle?api-version=2018-06-28 returned Error: connect ENOTSOCK C:/ProgramData/iotedge/workload/sock
Debugger attached.
C:\app\app.js:9
    throw err;
    ^

Error: connect ENOTSOCK C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

# Code sample exhibiting the issue:
```
'use strict';

var Transport = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').ModuleClient;
var Message = require('azure-iot-device').Message;

Client.fromEnvironment(Transport, function (err, client) {
  if (err) {
    throw err; // Throws error here
  }
...
}
```
# Console log of the issue:
```
2019-03-01T09:51:12.431Z azure-iot-http-base.RestApiClient sending GET call to /trust-bundle?api-version=2018-06-28
2019-03-01T09:51:12.437Z azure-iot-http-base.RestApiClient GET call to /trust-bundle?api-version=2018-06-28 returned Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
Debugger attached.
C:\app\app.js:9
    throw err;
    ^

Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```
and
```
2019-03-01T09:57:38.893Z azure-iot-http-base.RestApiClient sending GET call to /trust-bundle?api-version=2018-06-28
2019-03-01T09:57:38.903Z azure-iot-http-base.RestApiClient GET call to /trust-bundle?api-version=2018-06-28 returned Error: connect ENOTSOCK C:/ProgramData/iotedge/workload/sock
Debugger attached.
C:\app\app.js:9
    throw err;
    ^

Error: connect ENOTSOCK C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

AB#7366635

**Comment by pierreca** [comment]
@Griffrez  thanks for reporting this. it looks like this might be related to the support of unix domain sockets on Windows, which we haven't looked into with the Node SDK yet. 

The workaround I'd suggest for now is to change the edge config to use HTTP workload URIs while we work this from the backlog into our sprints (unlikely to happen before April unfortunately)

**Comment by Griffrez** [comment]
How am I supposed to figure out the HTTP workload URI?

**Comment by pierreca** [comment]
good question - I thought we had that documented somewhere but I can't find it.
In your `/etc/iotedge/config.yaml` you can find the connect and listen sections and alter them like so:

```yaml
connect:
  management_uri: "http://<YOUR_IP>:8081"
  workload_uri: "http://<YOUR_IP>:8080"
  #management_uri: "unix:///var/run/iotedge/mgmt.sock"
  #workload_uri: "unix:///var/run/iotedge/workload.sock"

listen:
  management_uri: "http://0.0.0.0:8081"
  workload_uri: "http://0.0.0.0:8080"
  #management_uri: "fd://iotedge.mgmt.socket"
  #workload_uri: "fd://iotedge.socket"
```

Then you can set the `IOTEDGE_WORKLOADURI` env variable used by your module code to match your config.yaml.

if you want to see a list of all env variables used by an edge module you can refer to https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/module_client.ts#L402

**Comment by gbbiotwesouth** [comment]
Any update on when this will be fixed?

**Comment by pierreca** [comment]
@gbbiotwesouth as far as I understand from the current nodejs docs, the required components in the runtime are not there yet for us to implement this feature:
https://nodejs.org/api/net.html#net_ipc_support

**Comment by KamalAman** [comment]
This limitation really should be properly documented somewhere on how to work around this issue and not left as an issue ticket with incomplete information on a solution.

**Comment by elhorton** [comment]
Agreed @KamalAman , thanks for contributing here! We are going to close this issue, as we have no plans to support Unix domain sockets in the Node SDK. The official guidance from IoT Edge is to use [Linux containers](https://techcommunity.microsoft.com/t5/internet-of-things/linux-modules-with-azure-iot-edge-on-windows-10-iot-enterprise/ba-p/1407066) on Windows devices. IoT Edge on Node is scoped to Linux and is documented [on this page](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module#solution-scope).

**Comment by az-iot-builder-01** [comment]
@Griffrez, @iotblackbelt, @KamalAman, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
