### ISSUE TITLE
MQTT "premature close"

### ISSUE THREAD

**Issue by sgacond** [Azure/azure-iot-sdk-node#73]
# Context
- **OS and version used:** Mac OS X 10.12.5 / Raspbian Jessie Lite
- **Node.js version:** 6.10.3
- **npm version:** 3.10.10
- **list of installed packages:** 
```
├─┬ azure-iot-device@1.1.17
│ ├─┬ azure-iot-common@1.1.11
│ │ └── crypto@0.0.3
│ ├── azure-iot-http-base@1.1.11
│ ├─┬ azure-storage@2.3.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ └── hash-base@3.0.4
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.81.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├── caseless@0.12.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.1
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.1.4
│ │ │ │ └── asynckit@0.4.0
│ │ │ ├─┬ har-validator@4.2.1
│ │ │ │ ├─┬ ajv@4.11.8
│ │ │ │ │ ├── co@4.6.0
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │ │ │   └── jsonify@0.0.0
│ │ │ │ └── har-schema@1.0.5
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├── boom@2.10.1
│ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └── sntp@1.0.9
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   └── assert-plus@1.0.0
│ │ │ │ └─┬ sshpk@1.13.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├── bcrypt-pbkdf@1.0.1
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── ecc-jsbn@0.1.1
│ │ │ │   ├─┬ getpass@0.1.7
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.16
│ │ │ │ └── mime-db@1.29.0
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── performance-now@0.2.0
│ │ │ ├── qs@6.4.0
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.2
│ │ │ │ └── punycode@1.4.1
│ │ │ └── tunnel-agent@0.6.0
│ │ ├── underscore@1.8.3
│ │ ├── uuid@3.1.0
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.8
│ │ └── ms@2.0.0
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
└─┬ azure-iot-device-mqtt@1.1.17
  └─┬ mqtt@1.14.1
    ├─┬ commist@1.0.0
    │ └── leven@1.0.2
    ├─┬ concat-stream@1.6.0
    │ ├─┬ readable-stream@2.3.3
    │ │ └── string_decoder@1.0.3
    │ └── typedarray@0.0.6
    ├─┬ end-of-stream@1.4.0
    │ └─┬ once@1.4.0
    │   └── wrappy@1.0.2
    ├─┬ help-me@1.1.0
    │ ├── callback-stream@1.1.0
    │ ├─┬ glob-stream@6.1.0
    │ │ ├── extend@3.0.1
    │ │ ├─┬ glob@7.1.2
    │ │ │ ├── fs.realpath@1.0.0
    │ │ │ ├── inflight@1.0.6
    │ │ │ ├─┬ minimatch@3.0.4
    │ │ │ │ └─┬ brace-expansion@1.1.8
    │ │ │ │   ├── balanced-match@1.0.0
    │ │ │ │   └── concat-map@0.0.1
    │ │ │ └── path-is-absolute@1.0.1
    │ │ ├─┬ glob-parent@3.1.0
    │ │ │ ├─┬ is-glob@3.1.0
    │ │ │ │ └── is-extglob@2.1.1
    │ │ │ └── path-dirname@1.0.2
    │ │ ├── is-negated-glob@1.0.0
    │ │ ├── ordered-read-streams@1.0.1
    │ │ ├── pumpify@1.3.5
    │ │ ├─┬ readable-stream@2.3.3
    │ │ │ └── string_decoder@1.0.3
    │ │ ├── remove-trailing-separator@1.1.0
    │ │ ├─┬ to-absolute-glob@2.0.1
    │ │ │ ├─┬ extend-shallow@2.0.1
    │ │ │ │ └── is-extendable@0.1.1
    │ │ │ └─┬ is-absolute@0.2.6
    │ │ │   ├─┬ is-relative@0.2.1
    │ │ │   │ └─┬ is-unc-path@0.1.2
    │ │ │   │   └── unc-path-regex@0.1.2
    │ │ │   └── is-windows@0.2.0
    │ │ └─┬ unique-stream@2.2.1
    │ │   └── through2-filter@2.0.0
    │ └─┬ through2@2.0.3
    │   └─┬ readable-stream@2.3.3
    │     └── string_decoder@1.0.3
    ├── inherits@2.0.3
    ├── minimist@1.2.0
    ├─┬ mqtt-connection@2.1.1
    │ ├─┬ reduplexer@1.1.0
    │ │ └─┬ readable-stream@1.0.34
    │ │   └── isarray@0.0.1
    │ └─┬ through2@0.6.5
    │   └─┬ readable-stream@1.0.34
    │     └── isarray@0.0.1
    ├─┬ mqtt-packet@3.4.8
    │ └─┬ bl@0.9.5
    │   └─┬ readable-stream@1.0.34
    │     └── isarray@0.0.1
    ├── pump@1.0.2
    ├─┬ readable-stream@1.0.34
    │ └── isarray@0.0.1
    ├── reinterval@1.1.0
    ├── split2@2.1.1
    ├─┬ websocket-stream@3.3.3
    │ ├─┬ duplexify@3.5.1
    │ │ └── stream-shift@1.0.0
    │ └─┬ ws@1.1.4
    │   ├── options@0.0.6
    │   └── ultron@1.0.2
    └── xtend@4.0.1
```
- **cloned repo:** n/A (own repo and samplecode from npm)

# Description of the issue:
Yesterday, i had a connection problem for about 11 hours. Every attempt to connect ended with a "premature close" error. I was able to reproduce the error with 10 devices, 10 other devices using the amqp transport on the same IoT-Hub worked fine. While googling and doing investigation i found Issue #21 and had exactly the same behaviour. I switched connection keys to secondary key and changed the connection to another IoT Hub (Both S1 level).

I was also able to reproduce the error using the simple samplecode on npm. Even with a new created device identity.

Both tried IoT-Hubs are based in West-Europe.

Timestamps: 
Broken: Aug 19 around 06:00:00 UTC (logrotated away already)
Back alive: Aug 19 17:52:08 UTC

# Code sample exhibiting the issue:
[azure-iot-device-mqtt (Getting Started)](https://www.npmjs.com/package/azure-iot-device-mqtt)
The production code tries a reconnect every 10s, after the connection is broken (Cellular connection). The sample above was only fired once and had the same problem.

# Console log of the issue:  
_(produced by console.log(error callback argument))_
```
ERR { Error: premature close
    at TLSSocket.onclose (/Users/silvan/splcloud-src/SplCloud.SLM.Client/src-app/node_modules/end-of-stream/index.js:43:67)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7) transportError: [Circular] }
```
Unfortunately i had no idea how to produce a more verbose output. Since the issue was gone since yesterday evening I have no chance to produce it again.

Thanks for investigating!

Best regards, 
Silvan

**Comment by pierreca** [comment]
you can produce more debug output by setting the DEBUG environment variable to `*`. watch out though as it may print shared access keys - don't paste the log here without pruning it. 

we'd need to know your IoT Hub name to look at logs.

When you switched to the secondary key, did it fix the problem? I'm not sure I fully get that part.

**Comment by sgacond** [comment]
Unfortunately, I found the DEBUG-* setting after the connection was back online.

Changing to the secondary key didn't help. I also tried to use another device identity, that didn't help either.
The hub was: splcloud-hub.azure-devices.net.

Thanks in advance!

**Comment by pierreca** [comment]
@jtjk a little more context would be super helpful. what type of operations are you running, at what speed/frequency, etc. Hub name and timestamp for the issue if this is something you can communicate. 

I really appreciate the feedback, it's important for us to know that you are running into issue so that we can prioritize fixing it. But you have to imagine that if I knew what the problem was, I'd fix it. it might be in the SDK, might be in the mqtt dependency,  might be on the service side... These transient issues are a nightmare to debug. Without some context, there's not much I can do...

**Comment by jtjk** [comment]
I updated node version to 8.6 in my Beaglebone black. Amqp was working very well with old node 4.8.4. After update, I have been facing lot's of problems and Azure IoT is dropping connection every now and then. Usually the connection drops about 30 min after connected.

Because of the problems, I changed to mqtt to see if that works better. Now with mqtt, I am seeing this error usually right after my code is started and it is connecting to the hub. Many times after that I can connect without issues.

With my Mac, I am not seeing any issues.

**Comment by pierreca** [comment]
@jtjk So you only have one device running is that correct?
- Are you creating your `Client` object with `fromConnectionString()` or `fromSharedAccessSignature()`?
- Are you using an x509 certificate?
- Do you see the error on `Client.open()` or when another operation takes places (subscribing to C2D messages, sending telemetry, etc?

**Comment by jtjk** [comment]
I am creating client with "fromConnectionString" and without x509

I am seeing error mostly after Client.open, but I guess I have seen it in other cases as well. Unfortunately I did not have logging to file enabled when I was getting these and now I am back to amqp -protocol. If I am still facing problems with amqp, I try mqtt again. 

If you want to debug this, you should get simple sample, beaglebone black with current image and node 8.6. That's all you need and you will certainly get these errors with that. It might be that you can get same with any Linux-system

**Comment by pierreca** [comment]
@sgacond @jtjk just to rule this out, is it possible that you have multiple concurrent connections using the same device id?

**Comment by sgacond** [comment]
@pierreca No concurrent connections with same device id at the current version. I never had the problem again since then (3 to 10 connected devices since then). I'm watching to provide more output as soon as the problem comes back.
Is this basically a supported case, to have multiple connections with the same deviceid open (from the same device)? I'm thinking about creating an independent connected process for diagnostics and sw-update cases.

**Comment by pierreca** [comment]
it's not a supported case, each device id is supposed to have only one active connection at a time, and depending on the protocol that you use you may be disconnected forcefully. I had to ask to rule this out.

looking forward to see if you can generate more logs. In the meantime i'm working to enable a retry logic at the client level by the end of the week that should help mitigate the problem until we understand what is really creating it.

**Comment by sgacond** [comment]
Thanks for clarification! I'm looking forward to the SDK reconnect logic.

**Comment by pierreca** [comment]
SDK retry logic is currently in preview in #114 and will be released early next week.
I'm not entirely convinced this will "fix all the things" though because i've found while working on this that the Mqtt.js library we're using sometimes has weird ways of throwing errors (namely emitting error events on an object that hasn't been returned and therefore on which we cannot subscribe to the event, effectively preventing us from retrying). I'll dig more into it but i just want to manage expectations for the next release.

**Comment by jtjk** [comment]
Hi,

I was trying the preview with mqtt and that was not helping. It is still dropping connection. I will try amqp as well and also with the debug logs on.

**Comment by pierreca** [comment]
@sgacond @jtjk What kind of internet connectivity do your devices have?
I've tried to provoke this failure by playing with SAS token renewal intervals, bad keys, etc to no avail. I wonder if it might be a lower layer thing.

Also just to confirm, you're seeing this on Mqtt, not on MQTT over websockets, right? or both?

**Comment by jtjk** [comment]
Mqtt and amqp. Not withm mqtt over websockets. I have used all kind of internet connectios from LTE to fiber and device itself is connected with ethernet cable

**Comment by sgacond** [comment]
My case was MQTT (no websockets) over a Cellular connection (Huawei stick).
One of the kind of Modems that appear as a USB-Ethernet interface for the host system (results in a double NAT'ed connection).
The connection itself must have been ok, because I was connected over the same connection (reverse tunnel).

**Comment by pierreca** [comment]
thanks - still trying to understand the circumstances 'cause it seems I'm the only one never hitting the issue here. @jtjk just to be clear, you're hitting the "premature error" also with AMQP? it's not an MQTT specific thing? we gotta separate issues if those are separate.

**Comment by jtjk** [comment]
Hi,

I am not getting premature error with AMQP. My comment was actually more related to general problems where devices are not getting messages anymore. Sorry that I was mixing this with the other issue.

**Comment by pierreca** [comment]
@jtjk ok thanks for clarifying. If you would like to open a new issue for the AMQP stuff that you are seeing after upgrading to the latest (azure-iot-device@1.2.0 and azure-iot-device-amqp >= 1.2.1), feel free to do so. I'm going to try and regroup all folks encountering the "premature close" error here.

**Comment by pierreca** [comment]
Finally tracked down where that error was coming from! it's a generic error with simply a message that is returned by a dependency of a dependency and bubbled all the way up to the SDK. 

This error apparently happens when the socket on the server side is timed out, which is something that is "retryable". (I managed to get a repro by rewriting a minimal socket server that times out on purpose)

I added code to catch it and "cast" it properly (to a `NotConnectedError`) so that it triggers the retry logic properly. I just sent the pull request, and provided that it passes code review and our continuous integration pipeline, it should make it to the next release of the packages (at the end of the week).

**Comment by sgacond** [comment]
Awesome! Thank you very much! I'm looking forward to the new release.

**Comment by t-s** [comment]
I am not sure this issue can be closed. We have IoTHub  connections be closed over a short period of timr,  and it's brought fo down an entire client's site. We watch our metrics and watch in real time at connections being brought down, even after eliminating so many additional connection features to try to fix it on our part, I'd really like to get in touch with an engineer there. We have a full support contract and spend thousands are on architecture and expect full functionality,.

**Comment by YoDaMa** [comment]
Hey @t-s, could you open up a new issue? I recognize you might be seeing similar symptoms to this issue, however it's not practical to re-open this issue that has been closed for 2 years. 

I've also seen your comment in the other thread with bragma. We're trying to understand what exactly is happening in your use case so we can resolve your issues. In your issue filing, please include as much actionable detail as possible. The more pertinent info provided the better we can diagnose what's happening.

**Comment by t-s** [comment]
This is a new issue, I believe, separate from the one from the past. We use MQTT and from reading docs and comments it seems a move to AMQP would be more stable. Our gateways connect over LTE and now Wifi as a backup. Our snap simply collects bluetooth IOT information and boardcasts it to Azure.

Code below.

> On Nov 22, 2019, at 12:50 PM, Yoseph Maguire <notifications@github.com> wrote:
> 
> Hey @t-s, could you open up a new issue? I recognize you might be seeing similar symptoms to this issue, however it's not practical to re-open this issue that has been closed for 2 years.
> 
> I've also seen your comment in the other thread with bragma. We're trying to understand what exactly is happening in your use case so we can resolve your issues. In your issue filing, please include as much actionable detail as possible. The more pertinent info provided the better we can diagnose what's happening.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Connection to azure:
```
const azureClient = (connectionString, errCallback, deviceId) => {
  const SNAP = process.env.SNAP;
  const SNAP_DATA = process.env.SNAP_DATA + "/";
  const SNAP_DEPENDENCIES = SNAP + "/";
  const SNAP_CONSTANTS = require(SNAP_DEPENDENCIES + "auth/constants");
  const SNAP_NODE_MODULES = SNAP + "/client/node_modules/";
  var internet = require(SNAP_NODE_MODULES + "internet-available");

  const fs = require(SNAP_NODE_MODULES + "fs-extra");
  const path = require("path");
  const Client = require(SNAP_NODE_MODULES + "azure-iot-device").Client;
  const Protocol = require(SNAP_NODE_MODULES + "azure-iot-device-mqtt").Mqtt;
  const execute = require("child_process").exec;
  const constants = require(SNAP_DEPENDENCIES + "auth/constants");
  const uuidv5 = require(SNAP_NODE_MODULES + "uuid");
  var Message = require("azure-iot-device").Message;
  var recoverCycle = require(SNAP_DEPENDENCIES + "client/recovery");

  var sensor = null;
  var connected = false;
  var { queue, slack } = require(SNAP_DEPENDENCIES + "util");
  var lastScans = "[]";
  var redisClient = queue.init();

  const azureConfig = {
    interval: 60000,
    LEDPin: 5,
    messageMax: 256,
    credentialPath: "/home/admin/.iot-hub",
    i2cOption: {
      pin: 9,
      i2cBusNo: 1,
      i2cAddress: 119
    }
  };

  var client;

  const onCommand = function(request, response) {
    redisClient.get("device_id", function(err, id) {
      if (request.payload || 'echo "No command"') {
        const cmd = request.payload;

        slack.health(`Executing command on Gateway - ${id}`);

        var command = execute(cmd);
        command.stdout.on("data", function(data) {
          response.send(200, "Command - OUT: " + data.toString(), function(
            err
          ) {
            if (err) {
              console.error(
                "An error occured when sending a command response:\n" +
                  err.toString()
              );
            } else {
              console.log(
                "Response to method '" +
                  request.methodName +
                  "' sent successfully."
              );
            }
          });
        });
      }
    });
  };

  const onNetworkChange = function(request, response) {
    // Respond the cloud app for the direct method
    response.send(200, "Network change started", function(err) {
      if (err) {
        console.error(
          "An error occured when sending a network change response:\n" +
            err.toString()
        );
      } else {
        console.log(
          "Response to method '" + request.methodName + "' sent successfully."
        );
      }
    });

    // if ((request.payload || 'echo "No interfaces"')) {
    //   try {
    //     network(JSON.parse(request.payload), true)
    //   } catch (error) {
    //     network(request.payload, true)
    //   }
    // }
  };

  const onUploadFileBlob = function(request, response) {
    // Respond the cloud app for the direct method
    fs.stat(request.payload.file, function(err, stats) {
      const rr = fs.createReadStream(request.payload.file);
      response.send(200, "File uploading", function(err) {
        if (err) {
          console.error(
            "An error occured when sending a network change response:\n" +
              err.toString()
          );
        } else {
          console.log(
            "Response to method '" + request.methodName + "' sent successfully."
          );
        }
      });
      client.uploadToBlob(request.payload.file, rr, stats.size, function(err) {
        if (err) {
          console.error("Error uploading file: " + err.toString());
        } else {
          console.log("File uploaded");
        }
      });
    });
  };

  function receiveMessageCallback(msg) {
    var message = msg.getData().toString("utf-8");
    if (message) {
      const resp = JSON.parse(message);
      if ((resp || {}).type === "ble") {
        sensor = JSON.parse(resp.config);
        redisClient.set("sensors", resp.body, () => {});
        redisClient.set("sensorconfig", resp.config, () => {});
      }
    }
    client.complete(msg, () => {
      try {
        console.log("Receive message: " + message);
      } catch (error) {
        console.log(error);
      }
    });
  }

  function initClient(cb, isRecovery) {
    // fromConnectionString must specify a transport constructor, coming from any transport package.
    client = Client.fromConnectionString(connectionString, Protocol);
    if (!isRecovery) {
      cb(client);
    } else {
      recoverCycle(client);
    }
  }

  const onReboot = function(request, response) {
    // Respond the cloud app for the direct method
    response.send(200, "Reboot started", function(err) {
      if (err) {
        console.error(
          "An error occured when sending a method response:\n" + err.toString()
        );
      } else {
        console.log(
          "Response to method '" + request.methodName + "' sent successfully."
        );
      }
    });

    // Report the reboot before the physical restart
    var date = new Date();
    var patch = {
      iothubDM: {
        reboot: {
          lastReboot: date.toISOString()
        }
      }
    };

    redisClient.get("device_id", function(err, id) {
      // Get device Twin
      client.getTwin(function(err, twin) {
        if (err) {
          console.error("could not get twin");
        } else {
          twin.properties.desired.update(patch, function(err) {
            if (err) throw err;

            slack.health(`Rebooting Gateway - ${id}`);

            execute("reboot");
          });
        }
      });
    });
  };

  const hasError = (azure, err, errCallback) => {
    console.error("[IoT hub Client] Connect error: " + err.message);
    redisClient.get("config", (err, config) => {
      if (config) {
        redisClient.set("config_bak", config, () => {});
        fs.outputFileSync(
          SNAP_DATA + "config.bak.json",
          config,
          "utf8",
          err => {
            if (err) {
              console.log(err);
            }
          }
        );
      }
      let device = {};
      try {
        device = JSON.parse(config) || {};
      } catch (e) {}
      if (!device.deviceId) {
        client.get("config_frikh5", (err, config1) => {
          try {
            device = JSON.parse(config1) || {};
          } catch (e) {}
          if (!device.deviceId) {
            client.get("config_gribh5", (err, config2) => {
              try {
                device = JSON.parse(config2) || {};
              } catch (e) {}
              if (!device.deviceId) {
                client.get("sensorconfig", (err, config3) => {
                  try {
                    device = JSON.parse(config3) || {};
                    device.deviceId = config3.iothub_device_id;
                  } catch (e) {}
                  if (!device.deviceId) {
                    if (fs.existsSync(SNAP_DATA + "config.json")) {
                      const fileConfig = fs.readFileSync(
                        SNAP_DATA + "config.json",
                        "utf8"
                      );
                      if (fileConfig) {
                        redisClient.set("config", fileConfig, () => {});
                        try {
                          device = JSON.parse(fileConfig);
                        } catch (e) {}
                      }
                    }

                    if (!device.deviceId) {
                      if (fs.existsSync(SNAP_DATA + "config.bak.json")) {
                        const bakFileConfig = fs.readFileSync(
                          SNAP_DATA + "config.bak.json",
                          "utf8"
                        );
                        if (bakFileConfig) {
                          try {
                            device = JSON.parse(bakFileConfig);
                          } catch (e) {}
                        }
                      }

                      if (device.deviceId) {
                        redisClient.set("config", bakFileConfig, () => {});
                      }
                    }
                  }
                  if (device.deviceId) {
                    redisClient.set("device_id", device.deviceId, () => {});
                    slack.health(
                      `Gateway (${
                        device.deviceId
                      }) needs to be re-registered in Azure. Please delete the device (${
                        device.deviceId
                      }) in the azure portal. It will automatically register itself after under the same device id. After, create its "bleSensor" module and update the iothub access keys in small wonder.`
                    );
                    redisClient.set("config", JSON.stringify({}), () => {});
                    connected = false;
                    setTimeout(() => {
                      process.exit(0);
                    }, 120000);
                  } else {
                    setTimeout(errCallback, 15000);
                  }
                });
              }
            });
          }
        });
      } else {
        setTimeout(errCallback, 15000);
      }
    });
  };

  initClient(azure => {
    console.log("Attempting to open azure client connection");
    azure.open(err => {
      if (err) {
        connected = false;
        hasError(azure, err, errCallback);
      } else {
        connected = true;
        redisClient.get("config", (err, config) => {
          if (config) {
            fs.outputFileSync(
              SNAP_DATA + "config.json",
              config,
              "utf8",
              err => {
                if (err) {
                  console.log(err);
                }
              }
            );
          }
        });
        // set C2D and device method callback
        client.onDeviceMethod("reboot", onReboot);
        client.onDeviceMethod("command", onCommand);
        client.onDeviceMethod("networkChange", onNetworkChange);
        client.onDeviceMethod("uploadFileBlob", onUploadFileBlob);
        client.on("message", receiveMessageCallback);
        console.log("Connected");
        connected = true;

        var scanner = setInterval(() => {
          redisClient.get("scans", (err, scans) => {
            if (scans && scans != lastScans) {
              let parsed = JSON.parse(scans);
              const lastParsed = JSON.parse(lastScans);
              const lastParsedKeys = lastParsed.map(
                e => e.time + e["uuid"] + e["major"] + e["minor"]
              );
              let index = -1;
              for (let s in parsed) {
                index++;
                const k = s.time + s["uuid"] + s["major"] + s["minor"];
                if (lastParsedKeys.includes(k)) {
                  parsed.splice(index, 1);
                }
              }
              console.log(parsed);
              console.log("Sending beacon scans");
              var message = new Message(
                JSON.stringify({
                  type: "beacon",
                  ingestionBlock: parsed,
                  timestamp: Date.now()
                })
              );
              message.ack = "full";
              const uuid = uuidv5(SNAP_CONSTANTS.API.production, uuidv5.URL);
              message.messageId = uuid;

              client.sendEvent(message, function(err) {
                if (err) {
                  console.log(err.toString());
                } else {
                  console.log("Beacon scans sent to azure");
                  lastScans = scans;
                }
              });
            }
          });
        }, parseInt((sensor || {}).interval_post || 32) * 1000);

        var heartbeat = setInterval(() => {
          var message = new Message(
            JSON.stringify({
              type: "heartbeat",
              timestamp: Date.now()
            })
          );
          client.sendEvent(message, function(err) {
            if (err) {
              console.log(err.toString());
            } else {
              console.log("Heartbeat sent");
            }
          });
        }, 5000);

        setInterval(() => {
          client.getTwin((err, twin) => {
            if (err) {
              connected = false;
              azure.close();
              hasError(azure, err, errCallback);
            } else {
              redisClient.set(
                "config",
                JSON.stringify(twin.properties.desired),
                () => {}
              );
              connected = true;
            }
            azureConfig.interval =
              twin.properties.desired.interval || azureConfig.interval;
          });
        }, parseInt((sensor || {}).interval_update || 32) * 1000);
      }
    });
  }, false);

  var recoveryInterval = setInterval(() => {
    initClient(false, true);
  }, 300000);
};

module.exports = azureClient;
```

Connection to allow for bluetooth fetching:

```
(function() {
  const SNAP = process.env.SNAP;
  const SNAP_DEPENDENCIES = SNAP + "/";
  const SNAP_DATA = process.env.SNAP_DATA + "/";
  const SNAP_NODE_MODULES = SNAP + "/bluetooth/node_modules/";
  const SNAP_CONSTANTS = require(SNAP_DEPENDENCIES + "auth/constants");

  const uuidv5 = require(SNAP_NODE_MODULES + "uuid");
  const {
    DeviceMethodRequest,
    DeviceMethodResponse,
    Message,
    Client
  } = require("azure-iot-device");

  const { map, sortBy, groupBy, merge } = require(SNAP_NODE_MODULES + "lodash");

  const moment = require(SNAP_NODE_MODULES + "moment");
  const fs = require(SNAP_NODE_MODULES + "fs-extra");

  const eTlm = "eddystoneTlm";

  const dMap = new Map();
  const edMap = new Map();

  var clientToClose = null;
  var lastScans = "[]";
  var redis = require(SNAP_NODE_MODULES + "redis");
  var BeaconScanner = require(SNAP_NODE_MODULES + "node-beacon-scanner");
  var internet = require(SNAP_NODE_MODULES + "internet-available");

  var { queue } = require(SNAP_DEPENDENCIES + "util");
  const { Mqtt } = require("azure-iot-device-mqtt");

  var cycleCount = 0;
  var bleModuleClient = null;

  var deviceId = null;
  var scanner = new BeaconScanner();
  var client = queue.init();
  var config = {};
  var uuids = [];
  var scans = [];
  var wearables = [];
  var hasInternet = false;

  internet()
    .then(() => {
      hasInternet = true;
    })
    .catch(() => {
      hasInternet = false;
    });

  const setScans = () => {
    const grouped = groupBy(
      // scans.filter((beacon) => {
      //   return beacon.accuracy < 10
      // }),
      scans,
      item => item["uuid"] + item["major"] + item["minor"]
    );
    if (grouped) {
      const mostAccurate = map(grouped, (group, k) => {
        return sortBy(group, item => item.accuracy)[0];
      }).filter(e => e);
      if (mostAccurate.length > 0) {
        const itemsUpload = mostAccurate.splice(
          -1 * (config.items_upload || 150)
        );
        if (hasInternet && itemsUpload.length > 0) {
          client.set("scans", JSON.stringify(itemsUpload));
        } else {
          client.get("scans", (err, reply) => {
            if (reply) {
              const parsed = JSON.parse(reply);
              client.set("scans", JSON.stringify([...parsed, ...itemsUpload]));
              client.get("networkoutagemanifest", (err, reply1) => {
                let manifest = {};
                if (reply1) {
                  manifest = JSON.parse(reply1);
                }
                if (Object.keys(manifest).length > 0) {
                  let data = [];
                  const date = new Date();
                  const key = date
                    .toLocaleString()
                    .replace(", ", "-")
                    .replace(/ /g, "-")
                    .replace(/\//g, "-")
                    .replace(/:/g, "-");
                  if (
                    (manifest[key] || {}).data &&
                    manifest[key].data.length > 0
                  ) {
                    data = manifest[key].data;
                  }
                  manifest[key] = {
                    filepath: SNAP_DATA + "network-outage-" + key + ".json",
                    data: JSON.stringify([...data, ...parsed, ...itemsUpload]),
                    uploaded: false
                  };
                  client.set("networkoutagemanifest", JSON.stringify(manifest));
                  fs.outputFileSync(manifest[key].filepath, manifest[key].data);
                } else {
                  if (
                    fs.existsSync(SNAP_DATA + "network-outage-manifest.json")
                  ) {
                    manifest = fs.readFileSync(
                      SNAP_DATA + "network-outage-manifest.json",
                      "utf-8"
                    );
                    if (Object.keys(manifest).length > 0) {
                    }
                    let data = [];
                    const date = new Date();
                    const key = date
                      .toLocaleString()
                      .replace(", ", "-")
                      .replace(/ /g, "-")
                      .replace(/\//g, "-")
                      .replace(/:/g, "-");
                    if (
                      (manifest[key] || {}).data &&
                      manifest[key].data.length > 0
                    ) {
                      data = manifest[key].data;
                    }
                    manifest[key] = {
                      filepath: SNAP_DATA + "network-outage--" + key + ".json",
                      data: JSON.stringify([
                        ...data,
                        ...parsed,
                        ...itemsUpload
                      ]),
                      uploaded: false
                    };
                    client.set(
                      "networkoutagemanifest",
                      JSON.stringify(manifest)
                    );
                    fs.outputFileSync(
                      manifest[key].filepath,
                      manifest[key].data
                    );
                  }
                }
              });
            }
          });
        }
      }
    }
  };

  const onAdvertisement = () => {
    scanner.onadvertisement = ad => {
      const { iBeacon, rssi } = ad;
      if (iBeacon) {
        const { uuid, major, minor, txPower } = iBeacon;
        if(dMap.get(ad.address) === undefined) {
          dMap.set(ad.address, uuid);
        }
        if (!edMap.get(ad.address)) {
            edMap.set(ad.address, [false, false]);
        }
        if (deviceId && uuid && major && minor) {
          const uuid_copy = uuid + major + minor;
          const index = uuids.length > 0 ? uuids.indexOf(uuid_copy.toLowerCase()) : -1;
          if (index > -1) {
            const txpower = parseInt(txPower || 1);
            const accuracy = Math.pow(12.0, 1.5 * (rssi / txpower - 1));
            const fields = {
              server_id: deviceId || false,
              time: moment(new Date()).toISOString(),
              txpower: txpower,
              accuracy: accuracy,
              uuid: uuid.toLowerCase(),
              major: major,
              minor: minor,
              rssi: rssi,
              battery: edMap.get(ad.address)[0] || false,
              temp: edMap.get(ad.address)[1] || false
            };
            console.log(fields);
            scans.push(fields);
          }
        }
      } else if (ad.beaconType == eTlm) {
        eddyValues = [ad.eddystoneTlm.batteryVoltage,
                      ad.eddystoneTlm.temperature]
        if (dMap.get(ad.address)) {
          edMap.set(ad.address, eddyValues)
        }
      }
    };
  };

  const setInfo = () => {
    client.get("device_id", (err, reply) => {
      if (reply) {
        deviceId = reply;
      }
    });
    client.get("sensorconfig", (err, reply) => {
      try {
        if (reply) {
          config = JSON.parse(reply)
        }
      } catch(e) {
        console.log(e);
      }
    })
    client.get("sensors", (err, reply) => {
      try {
        if (reply) {
          uuids = JSON.parse(reply) || [];
        }
      } catch (e) {
        console.log("No wearables: " + e);
      }
    });
  };

  const cycle = () => {
    setInfo();
    setTimeout(() => {
      setInfo();
      setScans();
      cycleCount++;
    }, parseInt(config.interval_collect || 18) * 1000);
  };

  const startScan = () => {
    console.log(`Starting bluetooth scan`);
    scanner
      .startScan()
      .then(() => {
        cycle();
      })
      .catch(e => {
        console.log(e);
      });
  };

  const load = () => {
    onAdvertisement();
    startScan();
  };

  load();

  setInterval(() => {
    console.log(`Restarting bluetooth cycle`);
    scanner.stopScan();
    load();
  }, parseInt((config || {}).interval_update || 24) * 1000);
})();
```

**Comment by YoDaMa** [comment]
Hey @t-s, could you please take what you've written and use it to create a new issue. Thanks 😃
