### ISSUE TITLE
Using `query.next()` with no parameters does not work as specified

### ISSUE THREAD

**Issue by khendry** [Azure/azure-iot-sdk-node#903]
# Context

- **OS and version used:** macOS 10.15.7
- **Node.js version:** 10.20.1
- **npm version:** 6.14.4

## Description of the issue

I'm implementing an HTTP triggered Azure function to query my DPS for the list of enrolment group registration states using the `azure-iot-provisioning-server` module. I create the client, construct the query spec and when I trigger the query using `query.next()` the function throws and error. 

When I modify the execution of the query, to use the query callback and wrap that in a promise, I can work around this issue. But the API does not seem to work as written. 

## Code sample exhibiting the issue

``` TypeScript
    // Inside and `async` function
    const dpsClient = ProvisioningServiceClient.fromConnectionString(dpsConnStr)
    const query = dpsClient.createEnrollmentGroupDeviceRegistrationStateQuery({
        query: '*'
    }, enrollmentGroupId, 500)
    const { responseBody } = await query.next()
    // BOOM!
```

## Console log of the issue

``` Console
LanguageWorkerConsoleLog[error]
Worker e6a958c5-7cb7-4abb-8ec4-77a5ea194d12 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): TypeError: actualCallback is not a function
     at ~/functions/node_modules/azure-iot-provisioning-service/dist/query.js:37:21
	 at requestCallback (~/functions/node_modules/azure-iot-http-base/dist/rest_api_client.js:142:17)     
	 at IncomingMessage.<anonymous> (~/functions/node_modules/azure-iot-http-base/dist/http.js:118:17)     
	 at IncomingMessage.emit (events.js:203:15)     
	 at endReadableNT (_stream_readable.js:1145:12)     
	 at process._tickCallback (internal/process/next_tick.js:63:19)
Executed 'Functions.things' (Failed, Id=80a1aa0c-7cf6-4464-bcb4-359cbded357e, Duration=760ms)
System.Private.CoreLib: Exception while executing function: Functions.things. System.Private.CoreLib: node exited with code 1
 LanguageWorkerConsoleLog[error] Worker e6a958c5-7cb7-4abb-8ec4-77a5ea194d12 uncaught exception (learn more:
 https://go.microsoft.com/fwlink/?linkid=2097909 ):
 TypeError: actualCallback is not a function     
 	at /~/functions/node_modules/azure-iot-provisioning-service/dist/query.js:37:21     
	 at requestCallback (~/functions/node_modules/azure-iot-http-base/dist/rest_api_client.js:142:17)     
	 at IncomingMessage.<anonymous> (~/functions/node_modules/azure-iot-http-base/dist/http.js:118:17)     
	 at IncomingMessage.emit (events.js:203:15)     
	 at endReadableNT (_stream_readable.js:1145:12)     
	 at process._tickCallback (internal/process/next_tick.js:63:19).
```

AB#8492768

**Comment by jebrando** [comment]
Thank you for the issue we will take a look and see if we can find an issue.

**Comment by BertKleewein** [comment]
@khendry - I got a fix for this committed to master, but I just missed the 11/2 release (1.8.7 I think).

**Comment by erikerikson** [comment]
The associated fix is neither in the official version or @latest.  Is there a release timeline?

**Comment by BertKleewein** [comment]
@erikerikson - I am checking with the release team

**Comment by anthonyvercolano** [comment]
This will be in the next release.  I am hoping within the next 10 days.

**Comment by anthonyvercolano** [comment]
Provisioning service client released.
