### ISSUE TITLE
warn: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by ksin63** [Azure/azure-iot-sdk-node#965]
# Context
Server OS
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
- **Docker version:**
19.03

- **Node version:**
node version: v10.23.2
npm version: 6.14.10

- **SDK version details:**
    "azure-iot-common": "1.12.4-lts0720up1",
    "azure-iot-device": "1.17.0-lts0720up1",
    "azure-iot-device-amqp": "1.13.0-lts0720up1",
    "azure-iot-provisioning-device": "1.8.4-lts0720up1",
    "azure-iot-provisioning-device-amqp": "1.8.4-lts0720up1",
    "azure-iot-security-x509": "1.7.4-lts0720up1",
    "azure-storage": "2.10.3",

- **list of installed packages:**
  "dependencies": {
    "@azure/storage-blob": "^12.3.0",
    "async": "2.6.1",
    "azure-iot-common": "1.12.4-lts0720up1",
    "azure-iot-device": "1.17.0-lts0720up1",
    "azure-iot-device-amqp": "1.13.0-lts0720up1",
    "azure-iot-provisioning-device": "1.8.4-lts0720up1",
    "azure-iot-provisioning-device-amqp": "1.8.4-lts0720up1",
    "azure-iot-security-x509": "1.7.4-lts0720up1",
    "azure-storage": "2.10.3",
    "better-queue": "3.8.10",
    "dockerode": "3.2.1",
    "fs-extra": "5.0.0",
    "https-proxy-agent": "2.2.3",
    "lodash": "4.17.19",
    "moment": "2.22.2",
    "mqtt": "2.18.5",
    "nedb": "1.8.0",
    "node-cache": "^5.1.2",
    "systeminformation": "4.30.5",
    "uuid": "3.3.2",
    "winston": "3.2.1"
  },
  "devDependencies": {
    "azure-event-hubs": "^0.2.6",
    "azure-iothub": "^1.9.1",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-prettier": "^3.0.0",
    "jest": "^25.3.0",
    "jest-junit": "^10.0.0",
    "nodemon": "^1.19.1",
    "pem": "^1.14.4",
    "prettier": "^1.15.3",
    "request": "^2.88.0",
    "wtfnode": "^0.6.0",
    "yargs": "^15.3.1"
  },

## Description of the issue
Post device authenticate with IoTHub when the device client either sends telemetry or tries to upload file. We are getting warning on console for 1 time 
warn: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
     at _addListener (events.js:256:17)
     at SenderLink.addListener (events.js:272:10)
     at /app/node_modules/azure-iot-device-amqp/dist/amqp.js:376:52
     at /app/node_modules/azure-iot-amqp-base/dist/amqp.js:423:33
     at constructor._onEnter (/app/node_modules/azure-iot-amqp-base/dist/sender_link.js:238:29)
     at constructor.transition (/app/node_modules/machina/lib/machina.js:653:28)
     at constructor.Fsm.(anonymous function) [as transition] (/app/node_modules/machina/lib/machina.js:466:63)
     at constructor.senderOpenEvent (/app/node_modules/azure-iot-amqp-base/dist/sender_link.js:175:36)
     at constructor.handle (/app/node_modules/machina/lib/machina.js:613:25)
     at constructor.Fsm.(anonymous function) [as handle] (/app/node_modules/machina/lib/machina.js:466:63) 

## Code sample exhibiting the issue
Occurring in random installation on few of the nodes, very sporadic in nature

## Console log of the issue

warn: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
     at _addListener (events.js:256:17)
     at SenderLink.addListener (events.js:272:10)
     at /app/node_modules/azure-iot-device-amqp/dist/amqp.js:376:52
     at /app/node_modules/azure-iot-amqp-base/dist/amqp.js:423:33
     at constructor._onEnter (/app/node_modules/azure-iot-amqp-base/dist/sender_link.js:238:29)
     at constructor.transition (/app/node_modules/machina/lib/machina.js:653:28)
     at constructor.Fsm.(anonymous function) [as transition] (/app/node_modules/machina/lib/machina.js:466:63)
     at constructor.senderOpenEvent (/app/node_modules/azure-iot-amqp-base/dist/sender_link.js:175:36)
     at constructor.handle (/app/node_modules/machina/lib/machina.js:613:25)
     at constructor.Fsm.(anonymous function) [as handle] (/app/node_modules/machina/lib/machina.js:466:63)

**Comment by vishnureddy17** [comment]
Possibly related to #957. Investigating.
